-- phpMyAdmin SQL Dump
-- version 3.4.10.1deb1
-- http://www.phpmyadmin.net
--
-- Servidor: localhost
-- Tiempo de generación: 20-09-2013 a las 09:30:31
-- Versión del servidor: 5.5.32
-- Versión de PHP: 5.3.10-1ubuntu3.8

SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de datos: `sitioweb2`
--

--
-- Volcado de datos para la tabla `ccontrataciones`
--

INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(1, 'NÂº CUCEY-IAPEY-CA-S-001-2012', 'MECANISMO QUE RIGE SEGÚN ATÍCULO 56 NUMERAL 1: Acto Único de recepción y apertura de sobres contentivos de: manifestación de voluntad de participar, documentos de Calificación y Ofertas.', 'MANTENIMIENTO DE MOTOCICLETAS SUZUKI DR650 ADSCRITAS A LA POLICÍA DEL ESTADO YARACUY', 'SERVICIO', 'INSTITUTO AUTÃ“NOMO DE POLICÃA DEL ESTADO YARACUY.', '11/09/2012', '18/09/2012', '8:30 a.m. a 12:00 p.m. 2:30 p.m a 4:30 p.m', 'Yaracuy', 'San Felipe', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', '500', 'Bicentenario', 'Corriente', '01750349980451025537', 'GobernaciÃ³n del Estado Yaracuy', 'Los interesados deben consignar al momento de retirar el Pliego de Condiciones en una carpeta identificada con el nombre y numero de Concurso los siguientes recaudos: 1) Carta  de solicitud del Pliego de Condiciones (en caso de presentarse el Representant', '11/09/2012', '13/09/2012', '9:00 a.m. a 11:00 a.m. y 2:00 p.m. a 4:00 p.m.', '17/09/2012', '10:00 a.m.', '19/09/2012 ', '09:00 a.m ', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(2, 'NÂº CUCEY-PROSALUD-CA-B-013-2012', 'MECANISMO QUE RIGE SEGÚN ATÍCULO 56 NUMERAL 1: Acto Único de recepción y apertura de sobres contentivos de: manifestación de voluntad de participar, documentos de Calificación y Ofertas.', 'ADQUISICIÓN DE MEDICINAS PARA LA RED PRIMARIA Y RED HOSPITALARIA DEL ESTADO YARACUY.', 'BIENES', 'Instituto AutÃ³nomo de la Salud del Estado Yaracuy (PROSALUD).', '12/09/2012', '19/09/2012', '8:30 a.m. a 12:00 p.m. 2:30 p.m a 4:30 p.m', 'Yaracuy', 'San Felipe', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', '500', 'Bicentenario', 'Corriente', '01750349980451025537', 'GobernaciÃ³n del Estado Yaracuy', 'Los interesados deben consignar al momento de retirar el Pliego de Condiciones en una carpeta identificada con el nombre y numero de Concurso los siguientes recaudos: 1) Carta  de solicitud del Pliego de Condiciones (en caso de presentarse el Representant', '12/09/2012', '14/09/2012', '9:00 a.m. a 11:00 a.m. y 2:00 p.m. a 4:00 p.m.', '18/09/2012', '09:00 a.m.', '20/09/2012', '09:00 a.m', 'Auditorio de PROSALUD, ubicado en el Callejón Cascabel entre Avenidas Cedeño y Ravell, Edificio PROSALUD, San Felipe, Estado Yaracuy.', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(3, 'CUCEY-PROSALUD-CA-B-014-2012', 'MECANISMO QUE RIGE SEGÚN ATÍCULO 56 NUMERAL 1: Acto Único de recepción y apertura de sobres contentivos de: manifestación de voluntad de participar, documentos de Calificación y Ofertas.', 'ADQUISICIÓN DE MATERIAL MÉDICO-QUIRÚRGICO PARA LA RED PRIMARIA Y RED HOSPITALARIA DEL ESTADO YARACUY.', 'BIENES', 'Instituto AutÃ³nomo de la Salud del Estado Yaracuy (PROSALUD).', '12/09/2012', '19/09/2012', '8:30 a.m. a 12:00 p.m. 2:30 p.m. a 4:30 p.m.', 'Yaracuy', 'San Felipe', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', '500', 'Bicentenario', 'Corriente', '01750349980451025537', 'GobernaciÃ³n del Estado Yaracuy', 'Los interesados deben consignar al momento de retirar el Pliego de Condiciones en una carpeta identificada con el nombre y numero de Concurso los siguientes recaudos: 1) Carta  de solicitud del Pliego de Condiciones (en caso de presentarse el Representant', '12/09/2012', '14/09/2012', '9:00 a.m. a 11:00 a.m. y 2:00 p.m. a 4:00 p.m.', '18/09/2012', '02:00 p.m.', '20/09/2012', '02:00 p.m.', 'Auditorio de PROSALUD, ubicado en el Callejón Cascabel entre Avenidas Cedeño y Ravell, Edificio PROSALUD, San Felipe, Estado Yaracuy.', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(4, 'CUCEY-IHAVEY-CA-O-001-2012', 'MECANISMO QUE RIGE SEGÚN ATÍCULO 56 NUMERAL 1: Acto Único de recepción y apertura de sobres contentivos de: manifestación de voluntad de participar, documentos de Calificación y Ofertas.', 'CULMINACION DE OBRAS DE URBANISMO EN LA URBANIZACIÓN ARAGUANEY, MUNICIPIO PEÑA, ESTADO YARACUY.', 'OBRAS', 'INSTITUTO DE HABITAT Y VIVIENDA DEL ESTADO YARACUY.', '24/09/2012', '04/10/2012', '8:30 a.m. a 11:30 p.m. 2:30 p.m. a 04:00 p.m.', 'Yaracuy', 'San Felipe', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.Sede de la Comisión Única d', '500', 'Bicentenario', 'Corriente', '01750349980451025537', 'GobernaciÃ³n del Estado Yaracuy', 'Los interesados deben consignar al momento de retirar el Pliego de Condiciones en una carpeta identificada con el nombre y numero de Concurso los siguientes recaudos: 1) Carta  de solicitud del Pliego de Condiciones (en caso de presentarse el Representant', '24/09/2012', '26/09/2012', '8:30 a.m. a 12:00 p.m. 2:30 p.m. a 4:00 p.m', '02/10/2012', '3:00 p.m.', '05/10/2012', '3:00 p.m.', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.Sede de la Comisión Única d', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(5, 'CUCEY-PROSALUD-CA-B-015-2012', '', 'ADQUISICIÓN DE REACTIVOS E INSUMOS DE LABORATORIO PARA LA RED HOSPITALARIA, RED PRIMARIA Y SALUD PÚBLICA DEL ESTADO YARACUY.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(6, 'CUCEY-GOB-CA-B-012-2012', '', 'ADQUISICIÓN DE CUARENTA (40) UNIDADES MOTORIZADAS PARA EL FORTALECIMIENTO DE LA POLICÍA DEL ESTADO YARACUY.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(7, 'CUCEY-ESAY-CA-O-002-2012', '', 'ESCARIFICACION, COLOCACION DE MEZCLA ASFALTICA Y CONSTRUCCION DE OBRAS DE DRENAJE EN LA VIA LO02, TRAMO PUEBLO NUEVO - EL CHINO, MUNICIPIO VEROES, ESTADO YARACUY.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(8, 'CUCEY-EMSOMY-CA-B-001-2012', '', 'ADQUISICIÓN E INSTALACIÓN DE MAQUINARIAS REQUERIDAS PARA EL FUNCIONAMIENTO DE DOS (02) PLANTAS PARA LA FABRICACIÓN DE BLOQUES DE CONCRETO', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(9, 'CUCEY-GOB-CA-S-001-2013', '', 'PRESTACIÓN DE SERVICIO EXEQUIALES DE PREVISIÓN FAMILIAR PARA TRABAJADORES VARIOS DEL EJECUTIVO REGIONAL, CORRESPONDIENTE AL AÑO 2013', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(10, 'CUCEY-GOB-CA-S-002-2013', '', 'PRESTACIÓN DEL SERVICIO DE ELABORACIÓN Y SUMINISTRO DE TICKET DE ALIMENTACIÓN PARA LOS TRABAJADORES Y LAS TRABAJADORAS DE LA GOBERNACIÓN  DEL ESTADO YARACUY Y DEMÁS ENTES DESCENTRALIZADOS ADSCRITOS AL MISMO, CORRESPONDIENTES AL AÑO 2013.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(11, 'CUCEY-FUNYABO-CA-S-001-2013', '', 'PLAN DE MANTENIMIENTO DRENAJES, DESMALEZAMIENTO, PODA Y LIMPIEZA DE LA AUTOPISTA CIMARRÓN ANDRESOTE ESTADO YARACUY.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(12, 'CUCEY-PROSALUD-CA-B-003-2013', '', 'ADQUISICIÓN DE MATERIAL MÉDICO-QUIRÚRGICO PARA LA RED PRIMARIA Y RED HOSPITALARIA DEL ESTADO YARACUY.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(13, 'CUCEY-IAI-CA-O-001-2013', '', 'CULMINACIÓN DE LA EMERGENCIA Y ÁREA DE TRAUMA SHOCK, HOSPITAL DEL MUNICIPIO NIRGUA, ESTADO YARACUY.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(14, 'CUCEY-IAI-CA-O-002-2013', '', 'CONSTRUCCIÓN DEL AMBULATORIO DE SALÓM, MUNICIPIO NIRGUA, ESTADO YARACUY.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(15, 'CUCEY-PROFUNIJESI-CA-B-001-2013', '', 'ADQUISICIÓN DE ALIMENTOS Y MISCELÁNEOS AÑO 2013, PARA  EL  INSTITUTO  AUTÓNOMO  DE LA SALUD DEL ESTADO YARACUY, LA FUNDACIÓN NIÑO JESÚS DEL ESTADO YARACUY, Y  LA  FUNDACIÓN REGIONAL “EL NIÑO SIMÓN” YARACUY.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(16, 'CUCEY-FUNDAPUSA-CA-B-001-2013', '', 'Adquisición de Marcapasos para la Fundación Pueblo Sano del Estado Yaracuy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(17, 'CUCEY-ESAY-CA-S-001-2013', '<p>MECANISMO QUE RIGE SEG&Uacute;N AT&Iacute;CULO 56 NUMERAL 1: Acto &Uacute;nico de recepci&oacute;n y apertura de sobres contentivos de: manifestaci&oacute;n de voluntad de participar, documentos de Calificaci&oacute;n y Ofertas.</p>', 'SERVICIO DE TRANSPORTE  DE CEMENTO ASFALTICO HASTA LA SEDE DE LA PLANTA DE LA EMPRESA SOCIALISTA ASFALTOS YARACUY, C.A.; UBICADA EN AUTOPISTA CIMARRÓN ANDRESOTE SENTIDO SAN FELIPE-BARQUISIMETO SECTOR EL PEÑÓN CHIVACOA MUNICIPIO BRUZUAL.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(18, 'CUCEY-PROSALUD-CA-B-004-2013', '<p>MECANISMO QUE RIGE SEG&Uacute;N AT&Iacute;CULO 56 NUMERAL 1: Acto &Uacute;nico de recepci&oacute;n y apertura de sobres contentivos de: manifestaci&oacute;n de voluntad de participar, documentos de Calificaci&oacute;n y Ofertas.</p>', 'ADQUISICIÓN DEL MATERIAL DE SÍNTESIS Y OSTEOSÍNTESIS PARA LAS ESPECIALIDADES DE TRAUMATOLOGÍA, MAXILOFACIAL, NEUROCIRUGÍA, UROLOGÍA Y CIRUGÍA EN GENERAL DEL ESTADO YARACUY, PARA EL AÑO 2013.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(19, 'CUCEY-SESTY-CA-B-001-2013', '<p>MECANISMO QUE RIGE SEG&Uacute;N AT&Iacute;CULO 56 NUMERAL 1: Acto &Uacute;nico de recepci&oacute;n y apertura de sobres contentivos de: manifestaci&oacute;n de voluntad de participar, documentos de Calificaci&oacute;n y Ofertas.</p>', 'ADQUISICIÓN DE DIEZ (10) MINIBÚS DE 32 PUESTOS', '', '', '', '', '', '', '', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', '', '', '', '', '', 'Los interesados deben consignar al momento de retirar el Pliego de Condiciones en una carpeta identificada con el nombre y numero de Concurso los siguientes recaudos: 1) Carta  de solicitud del Pliego de Condiciones (en caso de presentarse el Representant', '', '', '', '', '', '', '', '<p>Sede de la Comisi&oacute;n &Uacute;nica de Contrataciones de Bienes y Servicios de la Gobernaci&oacute;n del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.</p>', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(20, 'CUCEY-GOB-CA-B-001-2013', '<p>MECANISMO QUE RIGE SEG&Uacute;N AT&Iacute;CULO 56 NUMERAL 1: Acto &Uacute;nico de recepci&oacute;n y apertura de sobres contentivos de: manifestaci&oacute;n de voluntad de participar, documentos de Calificaci&oacute;n y Ofertas.</p>', 'ADQUISICIÓN DE MATERIALES DE OFICINA PARA LA GOBERNACIÓN DEL ESTADO YARACUY, Y DEMÁS ENTES DESCENTRALIZADOS ADSCRITOS A LA MISMA, CORRESPONDIENTES AL AÑO 2013.', '', '', '', '', '', '', '', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', '', '', '', '', '', 'Los interesados deben consignar al momento de retirar el Pliego de Condiciones en una carpeta identificada con el nombre y numero de Concurso los siguientes recaudos: 1) Carta  de solicitud del Pliego de Condiciones (en caso de presentarse el Representant', '', '', '', '', '', '', '', '<p>Sede de la Comisi&oacute;n &Uacute;nica de Contrataciones de Bienes y Servicios de la Gobernaci&oacute;n del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.</p>', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(21, 'CUCEY-IHAVEY-CA-O-001-2013', '<p>MECANISMO QUE RIGE SEG&Uacute;N AT&Iacute;CULO 56 NUMERAL 1: Acto &Uacute;nico de recepci&oacute;n y apertura de sobres contentivos de: manifestaci&oacute;n de voluntad de participar, documentos de Calificaci&oacute;n y Ofertas.</p>', 'CONSOLIDACIÓN DEL SECTOR LAS MERCEDES, III ETAPA, MUNICIPIO SAN FELIPE DEL ESTADO YARACUY.', '', '', '', '', '', '', '', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', '', '', '', '', '', 'Los interesados deben consignar al momento de retirar el Pliego de Condiciones en una carpeta identificada con el nombre y numero de Concurso los siguientes recaudos: 1) Carta  de solicitud del Pliego de Condiciones (en caso de presentarse el Representant', '', '', '', '', '', '', '', '<p>Sede de la Comisi&oacute;n &Uacute;nica de Contrataciones de Bienes y Servicios de la Gobernaci&oacute;n del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.</p>', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(22, 'CUCEY-GOB-CA-S-003-2013', '<p>MECANISMO QUE RIGE SEG&Uacute;N AT&Iacute;CULO 56 NUMERAL 1: Acto &Uacute;nico de recepci&oacute;n y apertura de sobres contentivos de: manifestaci&oacute;n de voluntad de participar, documentos de Calificaci&oacute;n y Ofertas.</p>', 'APROVISIONAMIENTO E INSTALACIÓN DE EQUIPOS GPS Y SERVICIO DE PLATAFORMA TECNOLÓGICA DE SEGUIMIENTO DE VEHÍCULOS (GRTMAX)', '', '', '', '', '', '', '', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', '', '', '', '', '', 'Los interesados deben consignar al momento de retirar el Pliego de Condiciones en una carpeta identificada con el nombre y numero de Concurso los siguientes recaudos: 1) Carta  de solicitud del Pliego de Condiciones (en caso de presentarse el Representant', '', '', '', '', '', '', '', '<p>Sede de la Comisi&oacute;n &Uacute;nica de Contrataciones de Bienes y Servicios de la Gobernaci&oacute;n del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.</p>', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(23, 'CUCEY-FUNYABO-CA-B-001-2013', '<p>MECANISMO QUE RIGE SEG&Uacute;N AT&Iacute;CULO 56 NUMERAL 1: Acto &Uacute;nico de recepci&oacute;n y apertura de sobres contentivos de: manifestaci&oacute;n de voluntad de participar, documentos de Calificaci&oacute;n y Ofertas.</p>', 'ADQUISICIÓN DE PINTURA PARA DEMARCACIÓN DE LA RED VIAL URBANA Y EXTRAURBANA DEL ESTADO YARACUY.', '', '', '', '', '', '', '', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', '', '', '', '', '', 'Los interesados deben consignar al momento de retirar el Pliego de Condiciones en una carpeta identificada con el nombre y numero de Concurso los siguientes recaudos: 1) Carta  de solicitud del Pliego de Condiciones (en caso de presentarse el Representant', '', '', '', '', '', '', '', '<p>Sede de la Comisi&oacute;n &Uacute;nica de Contrataciones de Bienes y Servicios de la Gobernaci&oacute;n del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.</p>', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(24, 'CUCEY-GOB-CA-B-002-2013', '<p>MECANISMO QUE RIGE SEG&Uacute;N AT&Iacute;CULO 56 NUMERAL 1: Acto &Uacute;nico de recepci&oacute;n y apertura de sobres contentivos de: manifestaci&oacute;n de voluntad de participar, documentos de Calificaci&oacute;n y Ofertas.</p>', 'ADQUISICIÓN DE MATERIALES DE LIMPIEZA PARA LA GOBERNACIÓN DEL ESTADO YARACUY, Y DEMÁS ENTES DESCENTRALIZADOS ADSCRITOS A LA MISMA, CORRESPONDIENTES AL AÑO 2013.', '', '', '', '', '', '', '', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', '', '', '', '', '', 'Los interesados deben consignar al momento de retirar el Pliego de Condiciones en una carpeta identificada con el nombre y numero de Concurso los siguientes recaudos: 1) Carta  de solicitud del Pliego de Condiciones (en caso de presentarse el Representant', '', '', '', '', '', '', '', '<p>Sede de la Comisi&oacute;n &Uacute;nica de Contrataciones de Bienes y Servicios de la Gobernaci&oacute;n del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.</p>', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(25, 'CUCEY-PROSALUD-CA-B-007-2013', '<p>MECANISMO QUE RIGE SEG&Uacute;N AT&Iacute;CULO 56 NUMERAL 1: Acto &Uacute;nico de recepci&oacute;n y apertura de sobres contentivos de: manifestaci&oacute;n de voluntad de participar, documentos de Calificaci&oacute;n y Ofertas.</p>', 'ADQUISICIÓN DE INSUMOS Y EQUIPOS DE ODONTOLOGÍA.', '', '', '', '', '', '', '', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', '', '', '', '', '', 'Los interesados deben consignar al momento de retirar el Pliego de Condiciones en una carpeta identificada con el nombre y numero de Concurso los siguientes recaudos: 1) Carta  de solicitud del Pliego de Condiciones (en caso de presentarse el Representant', '', '', '', '', '', '', '', '<p>Sede de la Comisi&oacute;n &Uacute;nica de Contrataciones de Bienes y Servicios de la Gobernaci&oacute;n del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.</p>', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(26, 'CUCEY-PROSALUD-CA-B-008-2013', '', 'ADQUISICIÓN DE MATERIAL DE SÍNTESIS Y OSTEOSÍNTESIS PARA LAS ESPECIALIDADES DE TRAUMATOLOGÍA, MAXILOFACIAL, NEUROCIRUGÍA, UROLOGÍA Y CIRUGÍA EN GENERAL DEL ESTADO YARACUY, (DESIERTOS 2013).', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(27, 'CUCEY-FUNDEY-CA-B-001-2013', 'MECANISMO QUE RIGE SEGÚN ATÍCULO 56 NUMERAL 1: Acto Único de recepción y apertura de sobres contentivos de: manifestación de voluntad de participar, documentos de Calificación y Ofertas.', 'ADQUISICIÓN DE ARTÍCULOS DEPORTIVOS DE ALTA COMPETENCIA, UNIFORMIDAD DE COMPETENCIA Y DE PRESENTACIÓN PARA SER UTILIZADO POR LA DELEGACIÓN DEL ESTADO YARACUY EN LOS VENIDEROS XIX JUEGOS DEPORTIVOS NACIONALES JUVENILES 2013.', '', '', '', '', '', '', '', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', '', '', '', '', '', 'Los interesados deben consignar al momento de retirar el Pliego de Condiciones en una carpeta identificada con el nombre y numero de Concurso los siguientes recaudos: 1) Carta  de solicitud del Pliego de Condiciones (en caso de presentarse el Representant', '', '', '', '', '', '', '', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(28, 'CUCEY-GOB-CA-B-003-2013', 'MECANISMO QUE RIGE SEGÚN ATÍCULO 56 NUMERAL 1: Acto Único de recepción y apertura de sobres contentivos de: manifestación de voluntad de participar, documentos de Calificación y Ofertas.', 'ADQUISICIÓN DE CAMIONES PARA LA GOBERNACIÓN DEL ESTADO YARACUY.', '', '', '', '', '', '', '', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', '', '', '', '', '', 'Los interesados deben consignar al momento de retirar el Pliego de Condiciones en una carpeta identificada con el nombre y numero de Concurso los siguientes recaudos: 1) Carta  de solicitud del Pliego de Condiciones (en caso de presentarse el Representant', '', '', '', '', '', '', '', 'Sede de la Comisión Única de Contrataciones de Bienes y Servicios de la Gobernación del Estado Yaracuy, ubicada en la Avenida Libertador con Avenida Caracas. Edificio Administrativo, Tercer Piso, San Felipe, Estado Yaracuy.', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(29, 'CUCEY-GOB-CA-B-004-2013', 'MECANISMO QUE RIGE SEGÚN ATÍCULO 56 NUMERAL 1: Acto Único de recepción y apertura de sobres contentivos de: manifestación de voluntad de participar, documentos de Calificación y Ofertas.', 'ADQUISICIÓN DE CAUCHOS PARA LOS VEHICULOS DE LA GOBERNACIÓN DEL ESTADO YARACUY Y SUS ENTES DESCENTRALIZADOS', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT IGNORE INTO `ccontrataciones` (`id`, `titulo`, `articulo`, `denominacion`, `actividad`, `ente`, `pfechad`, `pfechah`, `phorario`, `estado`, `municipio`, `lugar`, `costo`, `banco`, `tcuenta`, `ncuenta`, `benificiario`, `info`, `afechad`, `afechah`, `ahorario`, `rfechad`, `rhora`, `efecha`, `ehora`, `lugarsobres`, `status`) VALUES(30, 'CUCEY-GOB-CA-O-001-2013', 'MECANISMO QUE RIGE SEGÚN ATÍCULO 56 NUMERAL 1: Acto Único de recepción y apertura de sobres contentivos de: manifestación de voluntad de participar, documentos de Calificación y Ofertas.', 'REHABILITACI&#211;N DE LA V&#205;A YARITAGUA &#8211; EL POZON, MUNICIPIO PE&#209;A, ESTADO YARACUY.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);

--
-- Volcado de datos para la tabla `directory`
--

INSERT IGNORE INTO `directory` (`iddirectory`, `name`, `description`) VALUES(1, 'PALACIO DE GOBIERNO FRENTE A LA PLAZA BOLÍVAR', 'PALACIO DE GOBIERNO FRENTE A LA PLAZA BOLÍVAR\r\nSAN FELIPE, ESTADO YARACUY\r\nCENTRAL TELEFÓNICA 0254-2313276 ?2312597-2315112-2343028\r\nCORREO ELECTRÓNICO: gobier_bolivyaracuy@cantv.net\r\nDIRECCIÓN: 6ta Avenida con Avenida Caracas');
INSERT IGNORE INTO `directory` (`iddirectory`, `name`, `description`) VALUES(2, 'EDIFICIO ADMINISTRATIVO', 'AV. LIBERTADOR CRUCE CON AV. CARACAS');
INSERT IGNORE INTO `directory` (`iddirectory`, `name`, `description`) VALUES(3, 'Institutos Autónomos', '');
INSERT IGNORE INTO `directory` (`iddirectory`, `name`, `description`) VALUES(4, 'Instituciones Nacionales', '');
INSERT IGNORE INTO `directory` (`iddirectory`, `name`, `description`) VALUES(5, 'Consejo Legislativo Del Estado Yaracuy', '');
INSERT IGNORE INTO `directory` (`iddirectory`, `name`, `description`) VALUES(6, 'Diputados a La Asamblea Nacional', ' Av. Este 6, Esq. de Pajaritos, Edif. "José María Vargas" / Caracas - Venezuela ');

--
-- Volcado de datos para la tabla `directory_department`
--

INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(1, 'GOBERNADOR DEL ESTADO YARACUY', 'Palacio de Gobierno, Piso 2', 1);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(2, 'ASISTENTES GOBERNADOR', 'Palacio de Gobierno, Planta Alta', 1);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(3, 'SECRETARIO GENERAL DE GOBIERNO', 'Palacio de Gobierno, Planta Baja', 1);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(4, 'SECRETARÍO DE SEGURIDAD CIUDADANA', 'Palacio de Gobierno, Planta Baja', 1);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(5, 'SECRETARIA DEL DESPACHO', 'Palacio de Gobierno, Planta Baja', 1);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(9, 'SECRETARIA DE COMUNICACION E INFORMACION', '', 1);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(11, 'SERVICIO INTEGRAL DE EMERGENCIAS Y DENUNCIAS 0800-YARACUY.', '', 1);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(13, 'SECRETARIA DE FINANZAS Y ADMINISTRACION.', 'PISO 1', 2);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(14, 'SECRETARIA DE INFRAESTRUCTURA', '', 2);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(15, 'SECRETARIA DEL PODER COMUNAL Y PROTECCION SOCIAL', '', 2);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(16, 'DIRECCION DE ATENCION AL CIUDADANO.', 'Palacio de Gobierno, Planta Baja', 1);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(17, 'DIRECCION DE LA ZONA EDUCATIVA.', '', 2);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(18, 'SECRETARIA DE EDUCACION, CULTURA, DEPORTE Y JUVENTUD.', '', 2);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(19, 'INSTITUTO  DE CULTURA DEL ESTADO YARACUY (I.C.E.Y.)', '', 3);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(20, 'IMPRENTA DEL ESTADO YARACUY', ' Dirección: 6ta. Av. Entre Calles 8 Y 9 Al Lado De La Cley.', 3);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(21, 'FUNDACIÓN REGIONAL EL NIÑO SIMON', 'Calle Principal De Piedra Grande', 3);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(25, 'INSTITUTO AUTÓNOMO  PARA EL DEPORTE DEL EDO. YARACUY (FUNDEY)', '', 3);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(26, 'INSTITUTO AUTONOMO DE LA SALUD DEL ESTADO YARACUY (PROSALUD)', 'Callejón Cascabel, Entre Cedeño Y Ravell. ', 3);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(28, 'FUNDACIÓN PUEBLO SANO', '', 3);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(29, 'INSTITUTO AUTÓNOMO  DE DESARROLLO ECONÓMICO DEL ESTADO YARACUY (I.A.D.E.Y)', 'Centro Comercial La GalerÃ­a, Planta Baja', 3);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(30, 'SERVICIO AUTÓNOMO DE ADMINISTRACIÓN DE LA INFRAESTRUCTURA DEPORTIVA, CULTURAL Y TURÍSTICA DEL EDO. YARACUY. (S.A.I.E.Y)', 'Av. Alberto Ravell Centro De Convenciones Henrique Tirado Reyes.', 3);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(31, 'Instituto Autonomo  Contra La Pobreza Y Exclusion Social Del Estado Yaracuy.  (I.A.P.E.S.E.Y.)', '6ta. Av. Con Calles 22 Y 23 ', 3);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(33, 'Presidencia', '', 5);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(34, 'Vice-Presidencia', '', 5);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(35, 'Legisladores', '', 5);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(36, 'Diputados', 'Av. Este 6, Esq. de Pajaritos, Edif. "José María Vargas" / Caracas - Venezuela', 6);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(38, 'DIRECCIÓN DE INFORMATICA', 'PISO 2', 2);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(48, 'Secretario De Desarrollo Económico', 'Piso 8', 2);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(50, 'Dirección De Minas', 'Piso 8', 2);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(51, 'DIRECCION DE PROTOCOLO', ' Palacio de Gobierno, Planta Baja', 1);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(52, 'INSPECTORIA GENERAL DE GOBIERNO', ' Palacio de Gobierno, Planta Baja', 1);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(53, 'DIRECCIÓN DE CONSULTORÍA JURÍDICA', 'PISO 3', 2);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(54, 'DIRECCIÓN GENERAL DE BIENES.', 'Centro de Prensa', 2);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(55, 'SECRETARIA  PLANIFICACIÓN  Y DESARROLLO DE LA GOBERNACIÓN DEL ESTADO', '', 2);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(56, 'OFICINA DE PRESUPUESTO', 'PISO 4', 2);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(57, 'OFICINA DE RECURSOS HUMANOS', 'PISO 5, 6 y 7', 2);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(58, 'INSTITUTO AUTÓNOMO DE INFRAESTRUCTURA', '6ta. Av. Esq. calle 9', 3);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(59, 'INSTITUTO DE HABITAT Y VIVIENDA DEL ESTADO YARACUY', '7ma. Av. Esq. calle 7', 3);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(60, 'AGUAS DEL YARACUY', 'Calle La Mosca entre Av. Yaracuy y Av. Cedeño', 3);
INSERT IGNORE INTO `directory_department` (`iddirectory_department`, `name`, `address`, `iddirectory`) VALUES(61, 'DIRECTOR DEL INSTITUTO AUTÓNOMO DE AYUDA A LOS FUNCIONARIOS DE SEGURIDAD CIUDADANA DEL GOBIERNO BOLIVARIANO DE YARACUY (I.A.A)', 'Barrio Andrés Eloy Blanco Calle 03 con Av. 06, Municipio San Felipe', 3);

--
-- Volcado de datos para la tabla `directory_office`
--

INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(1, '', 'LCDO. JULIO CÉSAR LEON HEREDIA', '0254-2320772/2320992 ', 'gobernador@yaracuy.gob.ve', '@JULIOLEONYARA', 1);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(4, 'Secretario', 'PROF. JUAN TORREALBA.', 'TELF. 0254-2316024- 0416.635.26.60', 'secgeneraldegobierno@gmail.com', '', 3);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(6, 'Secretario', 'LCDO. ROGGER DAZA', '0254-2311752/0426.552.22.49 FAX 2314179', 'secdespachoyaracuy@gmail.com', '', 5);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(10, 'Secretario', 'LCDA AMNALY GUARNIERI', '0254-2316120/0426.552.22.37 FAX 2314175', 'prensayaracuy@gmail.com', '', 9);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(12, 'Coordinador', 'ING. IMARU BASTIDAS', '0426.546.46.91', 'csg@hotmail.com', '', 11);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(14, 'Secretario', 'LCDA. YAJAIRA ALVAREZ', '0254-2315766/0416.650.40.08', 'oyi@cantv.net', '', 13);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(16, 'DIRECTOR DE FINANZAS.', 'LCDA. PATRICIA ELIAS', '0254.231.57.66/0416.650.41.07', '', '', 13);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(18, 'DIRECTOR DE ADMINISTRACION', 'LCDA. YOLINA HERNANDEZ', '02542319158', '', '', 13);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(21, 'Secretario', 'ING. OTTO COLAIACOVO', '0254- 2319965/0416.654.03.56', 'armanguerrero@yahoo.es', '', 14);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(22, 'Secretario', 'LCDO. HUMBERTO SILVA.', '2310508/0416.650.68.03/0416.650.65.45', 'manuelherreragonzalez@hotmail.com', '', 15);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(23, 'DIRECTOR DE PODER COMUNAL', 'LCDA. MARIA MATILDE FERNANDEZ DE MURZI', '0412-0542227', 'marimurzi@gmail.com', '', 15);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(24, 'DIRECTOR DE PROTECCION SOCIAL (E)', 'ABG. LUIS ALEXANDER CASTILLO', '0424-5441221', 'luisalexandercastillo@gmail.com', '', 15);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(25, 'Director', 'LCDO. FRANCIS LINAREZ', '0416-5018656', '', '', 16);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(26, 'Director', 'PROF. MAURA BETANCOURT', '', '', '', 17);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(27, 'Secretario', 'PROF. MILENA HERNANDEZ DE RALDIRIZ.', '2310758/ 0426.557.61.22', 'maurabetancourt@hotmail.com', '', 18);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(28, 'Presidente', 'LCDO: JOSE RAFAEL NARANJO', '(0254) 2318711 Fax.(0254)2316636/0416.562', '', '', 19);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(29, 'JEFE DE TALLER', 'SR. EDGAR TOVAR', '', '', '', 20);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(30, 'Presidenta', 'LCDA. DELIA ZAVARCE DE LEÓN', ' 0254-2313485-2310259/0414.546.08.82', '', '', 21);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(31, 'Presidente', 'PROF. JUAN TORREALBA', '0254-2311346 ', '', '', 25);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(32, 'Presidenta', 'ING. ALEX SANCHEZ', '0254-2324419-2318505-2318482 Fax. 2314912 -2318911', '', '', 26);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(33, 'Presidenta', 'DRA. ANA MARIA MENDOZA', '', '', '', 28);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(34, 'PRESIDENTE', 'LCDO. GERARDO DELGADO', '0254-2318597 â€“ 2319757- Fax 2319008/0416.258.88.25/ 0416.501.71.14', 'presidenciaiadey@gmail.com ', '', 29);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(35, 'PRESIDENTE', 'ABOG. ALEXAMERY FRANCHESKY', 'Telf.0254-2319060/ 0416-150.84.11', '', '', 30);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(36, 'Presidente', 'Prof. Nabor Herrera', ' 0254- 2319023 â€“ 2324587/0412.850.10.36', '', '', 31);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(39, '', 'Leg. Shirley Romero', '', '', '', 35);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(40, '', ' Leg. Ivan Aparicio.', '', '', '', 35);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(41, '', 'Leg. Wendy Tellechea', '', '', '', 35);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(42, '', ' Leg. Angel Gamarra', '', '', '', 33);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(43, '', ' Leg.. Neidy Liscano. ', '0416-501.35.76  0424-538.6.66', '', '', 34);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(44, '', ' Leg. Henrys Mogollon', '', '', '', 35);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(45, '', ' Leg. Carmen Teresa Hernandez', '', '', '', 35);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(46, '', 'Dip. Braulio Alvarez', '0416-621.90.27. 0414-122.12.53', '', '', 36);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(47, '', ' Dip. Nestor Leon Heredia.', '', '', '', 36);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(48, '', ' Dip. Carlos Gamarra', '', '', '', 36);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(49, '', ' Dip. Yorman Aular', '', '', '', 36);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(50, 'Directora', 'ING. SOL MARIA COLMENAREZ', '0254-2325766/ 0416.0426.557.47.96', 'scolmenarez@yaracuy.gob.ve', '', 38);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(52, 'Secretario', ' ING. JOFFRE ALVARADO', '0254-2310049', 'joffrealvarado@gmail.com', '', 48);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(54, 'Director', 'T.S.U. JOSE RAFAEL MORALES', '', '', '', 50);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(55, 'Secretario', 'CNEL. ELEAZAR MALDONADO LEON. ', '0254-2312703/0426-552.12.10', '', '', 4);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(56, 'Directora', 'T.S.U. DALIANIS DE GOITIA', '0254- 2312591/0416.650.74.46 Ext. 101', '', '', 51);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(57, '', 'LCDO. LUIS MUÑOZ', '', '', '', 52);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(58, 'DIRECTOR DE EDUCACION', 'LCDA. ZORAIDA RIVAS', '', '', '', 18);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(59, 'DIRECTORA DE TESORERIA (E).', 'LCDA.  FATIMA LOPEZ', '0254- 2315766/0414546.96.11', '', '', 13);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(60, 'JEFE DE COMPRAS', 'SRA. MARÍA COLINA', '0426-7530461 - 2314663', '', '', 13);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(61, 'DIRECTOR', 'ABOG. PABLO BARRIOS', '', '', '', 53);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(62, 'SUPERVISOR DE MANTENIMIENTO DE LAS INSTALACIONES DEL PALACIO DE GOBIERNO', 'JUAN VICENTE GOMEZ', '2312591 / 2310744,  EXT. 119', '', '', 13);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(63, 'DIRECTOR', 'CNEL. OSWALDO CARDOZO', '0254-2312591 - 2310744', '', '', 54);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(64, 'Secretario', 'ING. RUBIGLARD PEREZ', '0416-5018718', 'rubyp3@hotmail.com', '', 55);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(65, 'Director', 'LCDO: KENNETH  FONTANIVE.', '0254-2310938/0416.654.09.42/0414.549.41.89', '', '', 56);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(66, 'DIRECTORA', 'ABOG. MARY NELLY VILLARROEL.', '0254-2343262/0414.393.62.38', '', '', 57);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(67, 'PRESIDENTE', 'ING. CESAR ALFREDO SANCHEZ BRACHO', '0254-2318220 - 2318153', '', '', 58);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(68, 'PRESIDENTE', 'ING. LEIDA GUDIÑO', '0254-2318754 / 2318615 / 0412-5153323 / 0412-5153337', '', '', 59);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(69, 'PRESIDENTE', 'ING. YALITZI GONZALEZ', '0254-2318078 - 2319446 - FAX 2345475', '', '', 60);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(70, 'PRESIDENTE', 'COMISIONADO AGREGADO BRAULIO MUÑOZ.', '0254- 2345362/ 0416.501.02.69', '', '', 61);
INSERT IGNORE INTO `directory_office` (`iddirectory_office`, `office`, `attendant`, `phone`, `email`, `twitter`, `iddirectory_department`) VALUES(71, 'Asistente', 'LCDO. ROGGER DAZA', '0426-552.23.33 / 0254-231.17.52 / 0426-552.22.49 FAX 0254-231.41.79', 'roggerda@gmail.com', '', 2);

--
-- Volcado de datos para la tabla `file_gallery`
--

INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(1, '1_med_1343762406_1_ASFALTADO LA GALERIA (1).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(2, '1_med_1343762407_2_ASFALTADO LA GALERIA (2).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(3, '1_med_1343762407_3_ASFALTADO LA GALERIA (3).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(4, '1_med_1343762408_4_ASFALTADO LA GALERIA (4).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(5, '1_min_1343762408_1_ASFALTADO LA GALERIA (1).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(6, '1_min_1343762409_2_ASFALTADO LA GALERIA (2).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(7, '1_min_1343762409_3_ASFALTADO LA GALERIA (3).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(8, '1_min_1343762410_4_ASFALTADO LA GALERIA (4).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(9, '2_med_1343763826_1_ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA (169).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(10, '2_med_1343763827_2_ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA (210).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(11, '2_min_1343763828_1_ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA (169).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(12, '2_min_1343763828_2_ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA (210).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(13, '3_ppal_1343826716_1_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (1).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(14, '3_med_1343826717_2_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (1).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(15, '3_med_1343826717_3_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (36).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(16, '3_med_1343826718_4_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (37).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(17, '3_med_1343826718_5_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (38).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(18, '3_med_1343826719_6_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (39).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(19, '3_med_1343826719_7_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (40).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(20, '3_min_1343826720_2_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (1).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(21, '3_min_1343826720_3_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (36).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(22, '3_min_1343826721_4_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (37).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(23, '3_min_1343826721_5_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (38).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(24, '3_min_1343826722_6_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (39).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(25, '3_min_1343826722_7_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (40).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(26, '1_ppal_1343919787_1_ASFALTADO LA GALERIA (1).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(27, '1_med_1343919789_2_ASFALTADO LA GALERIA (1).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(28, '1_med_1343919790_3_ASFALTADO LA GALERIA (2).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(29, '1_med_1343919791_4_ASFALTADO LA GALERIA (3).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(30, '1_med_1343919791_5_ASFALTADO LA GALERIA (4).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(31, '1_min_1343919792_2_ASFALTADO LA GALERIA (1).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(32, '1_min_1343919793_3_ASFALTADO LA GALERIA (2).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(33, '1_min_1343919793_4_ASFALTADO LA GALERIA (3).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(34, '1_min_1343919794_5_ASFALTADO LA GALERIA (4).JPG', 'Archivo de la Galeria con titulo: Asfaltado la Galeria', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(35, '2_ppal_1344264302_1_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (106).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(36, '2_med_1344264302_2_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (8).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(37, '2_med_1344264302_3_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (12).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(38, '2_med_1344264303_4_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (63).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(39, '2_med_1344264303_5_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (70).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(40, '2_med_1344264303_6_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (85).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(41, '2_med_1344264304_7_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (98).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(42, '2_med_1344264304_8_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (118).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(43, '2_med_1344264304_9_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (119).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(44, '2_min_1344264305_2_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (8).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(45, '2_min_1344264305_3_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (12).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(46, '2_min_1344264305_4_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (63).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(47, '2_min_1344264305_5_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (70).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(48, '2_min_1344264305_6_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (85).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(49, '2_min_1344264306_7_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (98).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(50, '2_min_1344264306_8_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (118).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(51, '2_min_1344264306_9_ASFALTADO,CARTAGENA,AV LA PAZ,AV LA FUENTE,ZUMUCO (119).JPG', 'Archivo de la Galeria con titulo: ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(52, '3_ppal_1344265180_1_ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA (210).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(53, '3_med_1344265181_2_ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA (169).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(54, '3_med_1344265182_3_ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA (210).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(55, '3_min_1344265182_2_ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA (169).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(56, '3_min_1344265183_3_ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA (210).JPG', 'Archivo de la Galeria con titulo: ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(57, '4_ppal_1344265336_1_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (1).JPG', 'Archivo de la Galeria con titulo: entrega de canastilla', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(58, '4_med_1344265336_2_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (1).JPG', 'Archivo de la Galeria con titulo: entrega de canastilla', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(59, '4_med_1344265337_3_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (36).JPG', 'Archivo de la Galeria con titulo: entrega de canastilla', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(60, '4_med_1344265338_4_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (39).JPG', 'Archivo de la Galeria con titulo: entrega de canastilla', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(61, '4_med_1344265338_5_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (40).JPG', 'Archivo de la Galeria con titulo: entrega de canastilla', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(62, '4_min_1344265339_2_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (1).JPG', 'Archivo de la Galeria con titulo: entrega de canastilla', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(63, '4_min_1344265339_3_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (36).JPG', 'Archivo de la Galeria con titulo: entrega de canastilla', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(64, '4_min_1344265339_4_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (39).JPG', 'Archivo de la Galeria con titulo: entrega de canastilla', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(65, '4_min_1344265340_5_ENTREGA DE CANASTILLAS FUNDACION NIÃ‘O SIMON (40).JPG', 'Archivo de la Galeria con titulo: entrega de canastilla', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(66, '5_ppal_1344265425_1_GABINETE SUCRE (64).JPG', 'Archivo de la Galeria con titulo: gabinete de sucre', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(67, '5_med_1344265425_2_GABINETE SUCRE (41).JPG', 'Archivo de la Galeria con titulo: gabinete de sucre', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(68, '5_med_1344265426_3_GABINETE SUCRE (42).JPG', 'Archivo de la Galeria con titulo: gabinete de sucre', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(69, '5_med_1344265426_4_GABINETE SUCRE (64).JPG', 'Archivo de la Galeria con titulo: gabinete de sucre', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(70, '5_med_1344265426_5_GABINETE SUCRE (102).JPG', 'Archivo de la Galeria con titulo: gabinete de sucre', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(71, '5_med_1344265427_6_GABINETE SUCRE (133).JPG', 'Archivo de la Galeria con titulo: gabinete de sucre', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(72, '5_med_1344265427_7_GABINETE SUCRE (144).JPG', 'Archivo de la Galeria con titulo: gabinete de sucre', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(73, '5_min_1344265427_2_GABINETE SUCRE (41).JPG', 'Archivo de la Galeria con titulo: gabinete de sucre', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(74, '5_min_1344265427_3_GABINETE SUCRE (42).JPG', 'Archivo de la Galeria con titulo: gabinete de sucre', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(75, '5_min_1344265428_4_GABINETE SUCRE (64).JPG', 'Archivo de la Galeria con titulo: gabinete de sucre', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(76, '5_min_1344265428_5_GABINETE SUCRE (102).JPG', 'Archivo de la Galeria con titulo: gabinete de sucre', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(77, '5_min_1344265428_6_GABINETE SUCRE (133).JPG', 'Archivo de la Galeria con titulo: gabinete de sucre', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(78, '5_min_1344265428_7_GABINETE SUCRE (144).JPG', 'Archivo de la Galeria con titulo: gabinete de sucre', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(79, '6_ppal_1344265494_1_GABINETE NUMERO 3 ARISTIDES BASTIDAS (294).JPG', 'Archivo de la Galeria con titulo: gabinete san pablo', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(80, '6_med_1344265495_2_GABINETE NUMERO 3 ARISTIDES BASTIDAS (174).JPG', 'Archivo de la Galeria con titulo: gabinete san pablo', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(81, '6_med_1344265495_3_GABINETE NUMERO 3 ARISTIDES BASTIDAS (175).JPG', 'Archivo de la Galeria con titulo: gabinete san pablo', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(82, '6_med_1344265496_4_GABINETE NUMERO 3 ARISTIDES BASTIDAS (204).JPG', 'Archivo de la Galeria con titulo: gabinete san pablo', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(83, '6_med_1344265497_5_GABINETE NUMERO 3 ARISTIDES BASTIDAS (210).JPG', 'Archivo de la Galeria con titulo: gabinete san pablo', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(84, '6_med_1344265497_6_GABINETE NUMERO 3 ARISTIDES BASTIDAS (252).JPG', 'Archivo de la Galeria con titulo: gabinete san pablo', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(85, '6_med_1344265498_7_GABINETE NUMERO 3 ARISTIDES BASTIDAS (294).JPG', 'Archivo de la Galeria con titulo: gabinete san pablo', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(86, '6_min_1344265498_2_GABINETE NUMERO 3 ARISTIDES BASTIDAS (174).JPG', 'Archivo de la Galeria con titulo: gabinete san pablo', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(87, '6_min_1344265499_3_GABINETE NUMERO 3 ARISTIDES BASTIDAS (175).JPG', 'Archivo de la Galeria con titulo: gabinete san pablo', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(88, '6_min_1344265499_4_GABINETE NUMERO 3 ARISTIDES BASTIDAS (204).JPG', 'Archivo de la Galeria con titulo: gabinete san pablo', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(89, '6_min_1344265500_5_GABINETE NUMERO 3 ARISTIDES BASTIDAS (210).JPG', 'Archivo de la Galeria con titulo: gabinete san pablo', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(90, '6_min_1344265500_6_GABINETE NUMERO 3 ARISTIDES BASTIDAS (252).JPG', 'Archivo de la Galeria con titulo: gabinete san pablo', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(91, '6_min_1344265500_7_GABINETE NUMERO 3 ARISTIDES BASTIDAS (294).JPG', 'Archivo de la Galeria con titulo: gabinete san pablo', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(92, '7_ppal_1344280381_1_CUPA AROA (234).JPG', 'Archivo de la Galeria con titulo: INAGURACION POZO CUPA MUNICIPIO BOLIVAR', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(93, '7_med_1344280381_2_CUPA AROA (234).JPG', 'Archivo de la Galeria con titulo: INAGURACION POZO CUPA MUNICIPIO BOLIVAR', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(94, '7_med_1344280382_3_CUPA AROA (237).JPG', 'Archivo de la Galeria con titulo: INAGURACION POZO CUPA MUNICIPIO BOLIVAR', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(95, '7_med_1344280382_4_CUPA AROA (250).JPG', 'Archivo de la Galeria con titulo: INAGURACION POZO CUPA MUNICIPIO BOLIVAR', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(96, '7_min_1344280383_2_CUPA AROA (234).JPG', 'Archivo de la Galeria con titulo: INAGURACION POZO CUPA MUNICIPIO BOLIVAR', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(97, '7_min_1344280383_3_CUPA AROA (237).JPG', 'Archivo de la Galeria con titulo: INAGURACION POZO CUPA MUNICIPIO BOLIVAR', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(98, '7_min_1344280384_4_CUPA AROA (250).JPG', 'Archivo de la Galeria con titulo: INAGURACION POZO CUPA MUNICIPIO BOLIVAR', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(99, '8_ppal_DSC_0228.JPG', 'Archivo de la Galeria con titulo: Gobernador Julio LeÃ³n continÃºa gobierno de calle', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(100, '8_med_DSC_0236.JPG', 'Archivo de la Galeria con titulo: Gobernador Julio LeÃ³n continÃºa gobierno de calle', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(101, '8_med_DSC_0247.JPG', 'Archivo de la Galeria con titulo: Gobernador Julio LeÃ³n continÃºa gobierno de calle', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(102, '8_med_DSC_0249.JPG', 'Archivo de la Galeria con titulo: Gobernador Julio LeÃ³n continÃºa gobierno de calle', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(103, '8_med_DSC_0276.JPG', 'Archivo de la Galeria con titulo: Gobernador Julio LeÃ³n continÃºa gobierno de calle', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(104, '8_min_DSC_0236.JPG', 'Archivo de la Galeria con titulo: Gobernador Julio LeÃ³n continÃºa gobierno de calle', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(105, '8_min_DSC_0247.JPG', 'Archivo de la Galeria con titulo: Gobernador Julio LeÃ³n continÃºa gobierno de calle', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(106, '8_min_DSC_0249.JPG', 'Archivo de la Galeria con titulo: Gobernador Julio LeÃ³n continÃºa gobierno de calle', 2, 1);
INSERT IGNORE INTO `file_gallery` (`idfile_gallery`, `filename`, `description`, `file_location_idfile_location`, `file_type_idfile_type`) VALUES(107, '8_min_DSC_0276.JPG', 'Archivo de la Galeria con titulo: Gobernador Julio LeÃ³n continÃºa gobierno de calle', 2, 1);

--
-- Volcado de datos para la tabla `file_location`
--

INSERT IGNORE INTO `file_location` (`idfile_location`, `name`, `location`) VALUES(1, 'news', 'media/images/news/');
INSERT IGNORE INTO `file_location` (`idfile_location`, `name`, `location`) VALUES(2, 'Galeria', 'media/images/gallery/');
INSERT IGNORE INTO `file_location` (`idfile_location`, `name`, `location`) VALUES(3, 'Portada', 'media/images/coverad/');

--
-- Volcado de datos para la tabla `file_type`
--

INSERT IGNORE INTO `file_type` (`idfile_type`, `mime_type`, `extencion`) VALUES(1, 'image/jpeg', '.jpg');

--
-- Volcado de datos para la tabla `gallery`
--

INSERT IGNORE INTO `gallery` (`idgallery`, `name`, `description`, `date`) VALUES(1, 'Asfaltado la Galeria', '', '2012-08-02');
INSERT IGNORE INTO `gallery` (`idgallery`, `name`, `description`, `date`) VALUES(2, 'ASFALTADO, CARTAGENA, AV LA PAZ, AV LA FUENTE, ZUMUCO', '', '2012-08-06');
INSERT IGNORE INTO `gallery` (`idgallery`, `name`, `description`, `date`) VALUES(3, 'ENTREGA DE BANDEJAS Y BECAS EN LA UNEFA', '', '2012-08-06');
INSERT IGNORE INTO `gallery` (`idgallery`, `name`, `description`, `date`) VALUES(4, 'entrega de canastilla', '', '2012-08-06');
INSERT IGNORE INTO `gallery` (`idgallery`, `name`, `description`, `date`) VALUES(5, 'gabinete de sucre', '', '2012-08-06');
INSERT IGNORE INTO `gallery` (`idgallery`, `name`, `description`, `date`) VALUES(6, 'gabinete san pablo', '', '2012-08-06');
INSERT IGNORE INTO `gallery` (`idgallery`, `name`, `description`, `date`) VALUES(7, 'INAGURACION POZO CUPA MUNICIPIO BOLIVAR', '', '2012-08-06');
INSERT IGNORE INTO `gallery` (`idgallery`, `name`, `description`, `date`) VALUES(8, 'Gobernador Julio LeÃ³n continÃºa gobierno de calle', 'Con la finalidad de conocer a fodo y de cerca las necesidades de las comunidades, y cumpliendo con los lineamientos emanados por el Presidente, NicolÃ¡s Maduro. El Gobernador, Julio LeÃ³n en compaÃ±Ã­a de su tren ejecutivo visitÃ³ el sector Recta de Apolonio en el municipio Independencia, a fin de efectÃºar una Asamblea de Ciudadanos.', '2013-05-03');

--
-- Volcado de datos para la tabla `gallery_has_file`
--

INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(1, 26, 'ppal');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(1, 27, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(1, 28, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(1, 29, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(1, 30, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(1, 31, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(1, 32, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(1, 33, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(1, 34, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 35, 'ppal');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 36, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 37, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 38, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 39, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 40, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 41, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 42, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 43, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 44, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 45, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 46, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 47, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 48, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 49, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 50, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(2, 51, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(3, 52, 'ppal');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(3, 53, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(3, 54, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(3, 55, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(3, 56, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(4, 57, 'ppal');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(4, 58, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(4, 59, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(4, 60, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(4, 61, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(4, 62, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(4, 63, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(4, 64, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(4, 65, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(5, 66, 'ppal');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(5, 67, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(5, 68, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(5, 69, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(5, 70, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(5, 71, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(5, 72, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(5, 73, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(5, 74, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(5, 75, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(5, 76, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(5, 77, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(5, 78, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(6, 79, 'ppal');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(6, 80, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(6, 81, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(6, 82, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(6, 83, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(6, 84, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(6, 85, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(6, 86, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(6, 87, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(6, 88, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(6, 89, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(6, 90, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(6, 91, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(7, 92, 'ppal');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(7, 93, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(7, 94, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(7, 95, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(7, 96, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(7, 97, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(7, 98, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(8, 99, 'ppal');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(8, 100, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(8, 101, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(8, 102, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(8, 103, 'med');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(8, 104, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(8, 105, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(8, 106, 'min');
INSERT IGNORE INTO `gallery_has_file` (`idgallery`, `idfile`, `type`) VALUES(8, 107, 'min');

--
-- Volcado de datos para la tabla `profile`
--

INSERT IGNORE INTO `profile` (`idprofile`, `name`, `description`, `status`) VALUES(1, 'Owner', 'Super Administrador', 0);
INSERT IGNORE INTO `profile` (`idprofile`, `name`, `description`, `status`) VALUES(2, 'Ccontrataciones', 'Comision de contrataciones', 0);
INSERT IGNORE INTO `profile` (`idprofile`, `name`, `description`, `status`) VALUES(3, 'Prensa', '', 0);

--
-- Volcado de datos para la tabla `user`
--

INSERT IGNORE INTO `user` (`iduser`, `nameuser`, `password`, `role`, `creation`) VALUES(1, 'root', '6368639483001dff4bd9c3511c587ee9eb730def4f2458b3ca539e7605d73b5f', '', NULL);

--
-- Volcado de datos para la tabla `user_has_profile`
--

INSERT IGNORE INTO `user_has_profile` (`user_iduser`, `profile_idprofile`) VALUES(1, 3);
INSERT IGNORE INTO `user_has_profile` (`user_iduser`, `profile_idprofile`) VALUES(1, 2);
INSERT IGNORE INTO `user_has_profile` (`user_iduser`, `profile_idprofile`) VALUES(1, 1);

--
-- Volcado de datos para la tabla `videoyoutubegrupo`
--

INSERT IGNORE INTO `videoyoutubegrupo` (`id`, `nombre`) VALUES(1, 'Portada');
INSERT IGNORE INTO `videoyoutubegrupo` (`id`, `nombre`) VALUES(2, 'Rindiendo Cuentas');
SET FOREIGN_KEY_CHECKS=1;

--
-- Activacion de las noticias
--
UPDATE `article` SET `prominent`=1, `status`=1;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
