<article>
	<div class="more_article">
		<div class="title_section cufon_myriad">Flora</div>
		<div style="text-align:center"><img src="<?php print PATH_SYSTEM . 'media/informacion/yaracuy/' . 'esteros.jpg'; ?>" /></div>
		<div>En el estado Yaracuy, la vegetaci&oacute;n se caracteriza por ser de sabana, selva nublada y bosques de galer&iacute;a, estos &uacute;ltimos se forman en las m&aacute;rgenes de los r&iacute;os. En el estado Yaracuy el 39% de sus tierras presentan condiciones favorables para el desarrollo de la actividad agr&iacute;cola, de las cuales un 15% corresponde a tierras de muy alto potencial, localizadas en la depresi&oacute;n Turbio-Yaracuy y en el Valle de Aroa, &aacute;reas que gozan de una excelente ubicaci&oacute;n geogr&aacute;fica y accesibilidad respecto a los mayores mercados del pa&iacute;s; el 24% restante corresponde a tierras de moderado a bajo potencial.</div>
		<p>Los recursos forestales del Yaracuy son el algaborro, el bucare, el cedro, el jabillo, el mijao, el roble y el sam&aacute;n, maderas duras y blandas; dichos recursos est&aacute;n ubicados principalemnte en la Sierra de Aroa y en el Macizo de Nirgua. Estas zonas boscosas en gran porcentaje son las fuentes productoras de aguas para &aacute;reas de desarrollo agr&iacute;cola y para consumo humano en los valles de Aroa y Yaracuy, por lo tanto su conservaci&oacute;n es importante como zona protectora y reserva hidr&aacute;ulica. El &aacute;rbol emblem&aacute;tico del estado<br /> es el Chaguaramo o palma real de Venezuela.</p>
		<div style="text-align:center"><img src="<?php print PATH_SYSTEM . 'media/informacion/yaracuy/' . 'Flora_Tropical.jpg'; ?>"  width="70%" /></div>
	</div>
</article>
<article>
	<div class="more_article">
		<div class="title_section cufon_myriad">Fauna</div>
		<div id="post-body-9109165056091404353" class="post-body entry-content">La fauna de la zona est&aacute; representada por la danta, la lapa, el cunaguaro y el mono capuchino, en el orden de los mam&iacute;feros. Entre las aves se encuentran la perdiz de monta&ntilde;a, la camata, el quetzal dorado y el &aacute;guila blanquinegro. Abundan las serpientes venenosas como mapanare y rabo de candela, entre las no venenosas la reinita y tragavenado. Tambi&eacute;n encontramos en el Estado la rana marsupial, el sapito monta&ntilde;oso, etc.<br />
			<div style="text-align:center"><img src="<?php print PATH_SYSTEM . 'media/informacion/yaracuy/' . '6568264331048110.jpg'; ?>"  width="70%" /></div>
			<br /><br /> <strong>Especies en extinci&oacute;n:</strong><br /> Cuspa o Armadillo gigante (Priodontes maximus). Su h&aacute;bitat son selvas tropicales h&uacute;medas de las tierras llanas de los Estados Barinas, Portuguesa, Apure, Yaracuy, Bol&iacute;var y Amazonas.<br />
			<div style="text-align:center"><img src="<?php print PATH_SYSTEM . 'media/informacion/yaracuy/' . '21792274.jpg'; ?>"  width="70%" /></div>
			<br /> <br /> <br /> <strong>DANTA</strong><br /> <strong>Nombre Cient&iacute;fico:</strong>Tapirus terrestris<br /> <strong>Otros Nombres Comunes:</strong> danto, tapir, macho de monte.<br /> <strong>Descripci&oacute;n:</strong>pertenece al orden de los perisod&aacute;ctilos, que significa en griego "dedos desiguales", que agrupa a los &eacute;quidos, rinocer&oacute;ntidos y tap&iacute;ricos. Su caracter&iacute;stica primordial es que el dedo medio de sus miembros est&aacute; muy desarrollado y forma una cavidad llamada casco, mientras que el resto de hallan disminuidos o atrofiados. Puede llegar a medir 2 m. y medio sin la cola, lo que lo convierte en el mam&iacute;fero m&aacute;s grande de toda el &aacute;rea continental suramericana. Su peso es de 250 Kg. aproximadamente. El cuerpo es macizo y pesado, su cabeza es triengular y termina en una nariz movible que recuerda a la de los elefantes. Su capacidad de visi&oacute;n es mediocre y posee extremidades cortas. Su pelaje es corto con coloraciones entre pardas y negras. Son animales t&iacute;midos, nocturnos, solitarios.<br /> <br />
			<div style="text-align:center"><img src="<?php print PATH_SYSTEM . 'media/informacion/yaracuy/' . '230px-Central_American_Tapir-Belize20.jpg'; ?>"  /></div>
		</div>
		<div class="post-footer-line post-footer-line-1">&nbsp;</div>
	</div>
</article>