<article>
	<div class="more_article">
<p><strong>El Escudo</strong><br /> &nbsp;&nbsp;&nbsp; <br /> <img style="width: 113px; height: 117px; float: left;" src="http://www.yaracuy.net/wp-content/uploads/2009/10/escudo-de-yaracuy-506x550.jpg" alt="" align="middle" />&nbsp;&nbsp;&nbsp; <br /> Dise&ntilde;ado por el Dr. Pablo Emilio Avila y cuya leyenda her&aacute;ldica la redacto el Br. Trinidad Figueira, el escudo esta dividido diagonalmente en 2 cuarteles: en el superior se muestra un manojo de espigas, emblema de la uni&oacute;n y de la abundancia; el rastrillo, la hoz que lo acompa&ntilde;an y los picos se&ntilde;alados a ambos lados de la estrella, representan el trabajo, fuente de toda la prosperidad. En el inferior se observa una fortaleza que representa el Castillo de San Felipe, denominado hoy Libertador, construido con el impulso del cacao, para guardar a Puerto Cabello y a las Bocas del Yaracuy del comercio il&iacute;cito en la &eacute;poca de la dominaci&oacute;n espa&ntilde;ola.<br /> <br /> En el inferior se observa una fortaleza que representa el Castillo de San Felipe, denominado hoy Libertador, construido con el impulso del cacao, para guardar a Puerto Cabello y a las Bocas del Yaracuy del comercio il&iacute;cito en la &eacute;poca de la dominaci&oacute;n espa&ntilde;ola. Significa adem&aacute;s la entereza con que la poblaci&oacute;n de los Cerritos de Cocorote sostuvo sus aspiraciones en la lucha secular para alcanzar el titulo de Ciudad, dado en Sevilla, mediante justo proceso por el Rey Felipe V, el 6 de Noviembre de 1729, de quien la nueva poblaci&oacute;n edificada por los vecinos de dichos Cerritos de Cocorote tom&oacute; el nombre, estableciendo como patrono espiritual de ella al Apostol Felipe&nbsp;&nbsp; (San Felipe, actual capital del Estado).<br /> <br /> Las ramas de ca&ntilde;a y de cacao que van a los lados, atados por un lazo, que patentiza<br /> <br /> la soberan&iacute;a del Estado, dicen de los cultivos principales que le dan la vida propia. La estrella que corona al escudo es el Sol de la Libertad, que oriento a los varones yaracuyanos que en "triunfos llegaron donde tuvo sus templos el sol".</p>
<p style="text-align: justify;"><strong>La Bandera</strong></p>
<p style="text-align: justify;"><img src="http://200.11.197.75/web2/sistema/profile/media/imagenes/bandera%20pequena.jpg" alt="" width="119" height="94" align="left" />La Bandera se halla en tres franjas oblicuas desiguales: una de color de rojo que simboliza el esp&iacute;ritu ind&oacute;mito de los ind&iacute;genas que poblaron estas tierras que lucharon con gran voluntad contra la invasi&oacute;n Espa&ntilde;ola y el de los hombres que lucharon para lograr la autonom&iacute;a que hizo posible la creaci&oacute;n de la provincia de Yaracuy en 1855, inicio hoy es Estado Yaracuy.</p>
<p style="text-align: justify;">Rojo:</p>
<p style="text-align: justify;">Simboliza el esp&iacute;ritu ind&oacute;mito de nuestros indios jiraharas, quienes lucharon con f&eacute;rrea voluntad</p>
<p style="text-align: justify;">contra la invasi&oacute;n espa&ntilde;ola y la de los h&eacute;roes del Cerrito Cocorote quienes despu&eacute;s de muchas luchas lograron la autonom&iacute;a de Yaracuy de la Provincia de Barquisimeto.</p>
<p style="text-align: justify;">Azul:</p>
<p style="text-align: justify;">Conjuntamente con el rojo y el amarillo, simboliza el respeto colectivo por nuestra Bandera Nacional. Al mismo tiempo simboliza los recursos h&iacute;dricos de que dispone la regi&oacute;n.</p>
<p style="text-align: justify;">Blanco:</p>
<p style="text-align: justify;">Simboliza el esp&iacute;ritu servicial que ha caracterizado por siempre a la regi&oacute;n yaracuyana y su gente.</p>
<p style="text-align: justify;">Amarillo, Azul y Verde (C&iacute;rculo):</p>
<p style="text-align: justify;">Sol, cielo y tierra se conjugan para exaltar las extraordinarias riquezas naturales del Estado y proyectar ante la Patria y ante el mundo sus potencialidades, privilegios y virtudes. DIAGONALES Concilian y armonizan todos los elementos en la Bandera, d&aacute;ndoles una percepci&oacute;n de marcha y movimiento.</p>
<p style="text-align: justify;">Cielo y Monta&ntilde;as (Dibujos):</p>
<p style="text-align: justify;">Representan la presencia del arte en este Estado que ha sido cuna de grandes artistas.</p>
<p style="text-align: justify;">Se instalar&aacute; como d&iacute;a de la bandera del Estado, el 28 de Marzo, d&iacute;a del Yaracuy, durante dicho d&iacute;a la Bandera permanecer&aacute; izada en el palacio de Gobierno y dem&aacute;s edificios p&uacute;blicos.</p>
<p style="text-align: justify;"><strong>Himno Regional</strong></p>
<p style="text-align: justify;">Siendo la m&uacute;sica del Prof. Ferm&iacute;n Abd&oacute;n Ram&iacute;rez, se instauro de hecho en la ciudad de San Felipe, capital del Estado Yaracuy el 8 de Junio de 1911, a&ntilde;o 102 de la Independencia y 53 de la Federaci&oacute;n. Y la letra de Pedro Mar&iacute;a Sosa, el cual procura construir para nuestro Yaracuy un canto al alcance de las masas populares sin alusiones mitol&oacute;gicas, se instaura el 19 de Abril de 1911.</p>
<p style="text-align: center;">Letra del Himno del Yaracuy<br /> Letra:Pedro Mar&iacute;a Sosa<br /> M&uacute;sica: Abd&oacute;n Ram&iacute;rez</p>
<p style="text-align: center;">Coro<br /> Alto la fama pregona<br /> mis gloriosas tradiciones<br /> la opulencia de mi zona<br /> la virtud de mis varones</p>
<p style="text-align: center;">I<br /> Dominaba la Espa&ntilde;a invasora<br /> mis extensas y ricas comarcas<br /> repletando, insaciable, sus arcas<br /> con la savia vital de mi flora.<br /> El soberbio castillo almenado<br /> que en el Puerto Cabello se ostenta<br /> fue construido con oro esquilmado<br /> a mi zona feraz, opulenta</p>
<p style="text-align: center;">&nbsp;II<br /> A tal punto lleg&oacute; la crueldad<br /> que mi pueblo con voz varonil<br /> en la fecha gloriosa de abril<br /> entusiasta grit&oacute;: &iexcl;LIBERTAD!<br /> Yo no quise acatar la Regencia<br /> y firm&eacute; con patri&oacute;tico empe&ntilde;o<br /> aquella acta en que el pueblo avile&ntilde;o<br /> con orgullo exclamo: &iexcl;Independencia!</p>
<p style="text-align: center;">III<br /> De Bol&iacute;var la f&uacute;lgida estrella<br /> con denuedo mis hijos siguieron<br /> y mis fueros sagrados hubieron<br /> en aquella sangrienta epopeya;<br /> persiguiendo al audaz espa&ntilde;ol<br /> mis guerreros en triunfo llegaron<br /> al Per&uacute; que tambien libertaron<br /> &iexcl;donde tuvo sus templos el SOL!</p>
<p style="text-align: center;">IV<br /> El progreso, esplendente fanal<br /> con su m&aacute;gica luz ilumina<br /> la semilla del bien que germina<br /> en mi hermoso jardin tropical;<br /> elementos contengo, prolijos,<br /> honra y prez de mi noble existencia;<br /> en la paz, en la guerra, en la ciencia,<br /> &iexcl;porque en todo culminan mis hijos!</p>
	</div>
</article>