<article>
	<div class="more_article" style="font-size: 90%;">
		<div class="title_section cufon_myriad">Institutos Descentralizados</div>
<ul style="font-size: 90%;">
<li><a href="#question_6">Aguas de Yaracuy C.A.</a></li>
<li><a href="#question_10">Instituto Aut&oacute;nomo de Policia del Estado Yaracuy (IAPEY)</a></li>
<li><a href="#question_13">Instituto Aut&oacute;nomo de Infraestructura del Estado Yaracuy (IAI)</a></li>
<li><a href="#question_17">Instituto Aut&oacute;nomo de Desarrollo Econ&oacute;mico del Estado Yaracuy (IADEY)</a></li>
<li><a href="#question_18">Instituto Aut&oacute;nomo de la Salud del Estado Yaracuy (PROSALUD)</a></li>
<li><a href="#question_19">Instituto Aut&oacute;nomo de Defensa Civil (IADC)</a></li>
<li><a href="#question_20">Fundaci&oacute;n Regional del Ni&ntilde;o Sim&oacute;n</a></li>
<li><a href="#question_23">Instituto Aut&oacute;nomo Cuerpo de Bomberos del Estado Yaracuy (IABOY)</a></li>
<li><a href="#question_25">Instituto Contra la Pobreza y la Exclusi&oacute;n Social del Estado Yaracuy (IAPESEY)</a></li>
<li><a href="#question_26">Instituto de Habitad y Vivienda del Estado Yaracuy</a></li>
<li><a href="#question_27">Servicio Aut&oacute;nomo de Administraci&oacute;n de las Infraestructuras del Estado Yaracuy (SAIEY)</a></li>
<li><a href="#question_28">Instituto Aut&oacute;nomo de Deporte del Estado Yaracuy (FUNDEY)</a></li>
<li><a href="#question_30">Instituto Aut&oacute;nomo de Ayuda de los Funcionarios de Seguridad Ciudadana del Estado Yaracuy (IAA)</a></li>
<li><a href="#question_77">Servicio Integral de Emegencias del Estado Yaracuy 171 </a></li>
</ul>
<hr />
<h3><a name="question_6"></a> Aguas de Yaracuy C.A.</h3>
<p><strong>Misi&oacute;n:</strong><br /> <br /> Garantizar el suministro de Agua Potable y Saneamiento de los Habitantes de el Estado Yaracuy.</p>
<p><strong>Visi&oacute;n:</strong><br /> <br /> Hacer de Aguas de Yaracuy, C.A: una empresa que garantice el suministro de Agua Potable y Saneamiento a los habitantes del Estado Yaracuy, en equilibrio con el ambiente y el bajo contexto de los objetivos estrat&eacute;gicos de la Naci&oacute;n.<br /> <br /> Objetivo:<br /> <br /> Mejorar la calidad y cobertura de los servicios de agua potable y saneamiento bajo un esquema administrativo y financiero de autogestion y congesti&oacute;n, a fin de garantizar un mejor servicio a los habitantes de el Estado Yaracuy.<br /> <br /> Direcci&oacute;n de Sucursales:<br /> <br /> Aroa telf: 0253-2271237<br /> Boraure telf :0254-5670053<br /> Cocorote telf: 0254-2323301<br /> Guama telf: 0254-5610850<br /> Chivacoa telf: 0254-8830186<br /> Urachiche telf: 0251-8860067<br /> Nirgua telf: 0254-5721556<br /> Sabana de Parra telf: 0251-888173<br /> Yaritagua telf: 0251-4820862<br /> San Felipe: e-mail: hidrologia@cantv.net Tel&eacute;fono(s): 0254-2341360 - 2345475<br /> Correo Electr&oacute;nico:aguasyaracuy@yaracuy.gob.ve</p>
<p> <a href="#top">^ Arriba</a>&nbsp;</p>
<h3><a name="question_10"></a> Instituto Aut&oacute;nomo de Policia del Estado Yaracuy (IAPEY)</h3>
<p>El Instituto Aut&oacute;nomo de Polic&iacute;a del Estado Yaracuy, se cre&oacute; con personalidad jur&iacute;dica y patrimonio independiente del Fisco del Estado en el a&ntilde;o de 1997. Su Misi&oacute;n es velar por la seguridad de las personas y sus bienes, as&iacute; como el mantenimiento de la moralidad, salubridad, urbanismo, turismo, defensa del ambiente, transito y orden publico en la jurisdicci&oacute;n del Estado Yaracuy.<br /> <br /> Direcci&oacute;n : Calle 9 entre Av 10 y 11.<br /> Tel&eacute;fono(s) : Directo 0254-2312824<br /> <br /> Correo Electr&oacute;nico : iapey@yaracuy.gob.ve</p>
<p> <a href="#top">^ Arriba</a>&nbsp;</p>
<h3><a name="question_13"></a> Instituto Aut&oacute;nomo de Infraestructura del Estado Yaracuy (IAI)</h3>
<p><strong>Misi&oacute;n:</strong><br /> <br /> Instituto aut&oacute;nomo orientado a la atenci&oacute;n y soluci&oacute;n de las necesidades de construcci&oacute;n, reparaci&oacute;n y mantenimiento de la infraestructura de la poblaci&oacute;n&nbsp; yaracuyana, con el compromiso de emplear los avances tecnol&oacute;gicos y promover la participaci&oacute;n ciudadana en el desarrollo de programas de cogesti&oacute;n a los fines de garantizar la mayor vida &uacute;til de las instalaciones como acci&oacute;n tendente a mejorar el bienestar social y desarrollo sustentable del estado Yaracuy</p>
<p><strong>Visi&oacute;n:</strong><br /> <br /> Ser un &oacute;rgano rector en la construcci&oacute;n, reparaci&oacute;n y mantenimiento de infraestructura en todas las &aacute;reas urbanas y rurales del estado Yaracuy, proyectando su imagen como potencia de desarrollo integrado a la comunidad bajo criterios de excelencia, valores y principios, credibilidad y el compromiso recontribuir en la construcci&oacute;n del nuevo estado.<br /> <br /> Objetivos:</p>
<ul>
<li>Ejecutar la construcci&oacute;n, reparaci&oacute;n y mantenimiento de la infraestructura f&iacute;sica que se requiere en las &aacute;reas de: Salud, Educaci&oacute;n, Cultura, Agr&iacute;cola, Ambiente, Turismo, Recreaci&oacute;n, Seguridad y Defensa&nbsp; en General, en cualquier otra &aacute;rea de inter&eacute;s colectivo en jurisdicci&oacute;n del Estado Yaracuy</li>
<li>Equipamiento integral de obras civiles de infraestructura f&iacute;sica y construcci&oacute;n de obras complementarias de inter&eacute;s colectivo en el Estado Yaracuy</li>
<li>Asumir las competencias inherentes a su objeto, derivados del proceso de descentralizaci&oacute;n y transferencia al estado, en materia y servicios que le sean atribuidas&nbsp; de conformidad con las leyes y sus reglamentos</li>
<li>Constituir empresas, fundaciones o servicios p&uacute;blicos, previo cumplimiento de las formalidades legales</li>
<li>Establecer convenios de cogesti&oacute;n o de ejecuci&oacute;n con los gobiernos municipales y servicios inherentes a su objeto, con la finalidad de desconcentrar y descentralizar sus actividades operativas y administrativas, conforme&nbsp; a la normativas legal aplicable</li>
</ul>
<p>Direcci&oacute;n: 6 Av. esquina Calle 9<br /> Tel&eacute;fono(s): Directo 0254-2318153/2318220<br /> Correo Electr&oacute;nico: iai@yaracuy.gob.ve</p>
<p> <a href="#top">^ Arriba</a>&nbsp;</p>
<h3><a name="question_17"></a> Instituto Aut&oacute;nomo de Desarrollo Econ&oacute;mico del Estado Yaracuy (IADEY)</h3>
<p>El Instituto Aut&oacute;nomo de Desarrollo Econ&oacute;mico del Estado Yaracuy fue creado con el prop&oacute;sito de Promover, Coordinar y Ejecutar pol&iacute;ticas, programas y proyectos que fomenten y consoliden el desarrollo econ&oacute;mico del Estado, en los sectores Agr&iacute;cola, Industrial, Turismo, Artesan&iacute;a, Comercio y Servicio, en base a las pol&iacute;ticas de desarrollo que permitan el impulso de tales sectores, mediante la promoci&oacute;n de acciones orientadas a programas de organizaci&oacute;n, capacitaci&oacute;n, asistencia t&eacute;cnica, financiamiento y apoyo en el proceso de comercializaci&oacute;n y mercadeo.<br /> <br /> <strong>Misi&oacute;n:</strong><br /> <br /> El nuevo IADEY est&aacute; llamado a liderar el dise&ntilde;o e implementaci&oacute;n de pol&iacute;ticas de desarrollo para el Estado Yaracuy, orientadas a satisfacer las necesidades de nuestra poblaci&oacute;n emprendedora, con el fin de elevar el nivel de vida de la poblaci&oacute;n y coadyudar a fortalecer la soberania econ&oacute;mica del pa&iacute;s, promoviendo los valores de Eficiencia, Calidad, Honestidad, Solidaridad y la Incorporaci&oacute;n de tecnologias.<br /> <br /> <strong>Visi&oacute;n:</strong><br /> <br /> El Instituto Aut&oacute;nomo de Desarrollo Econ&oacute;mico del Estado Yaracuy (IADEY), fomenta el crecimiento socioecon&oacute;mico de nuestra entidad federal sobre la base de los principios de Justicia Social, Democracia, Eficiencia, Libre Competencia, Protecci&oacute;n del Ambiente, Productividad y Solidaridad, mediante programasy proyectos que conjungan el financiamiento, la capacitaci&oacute;n y la asistencia t&eacute;cnica, a los fines de asegurar al desarrollo humano integra.<br /> <br /> Objetivo:<br /> <br /> dise&ntilde;ar, Promover, Coordinar y ejecutar politicas, programas y proyectos que propicien, fomento y consoliden el desarrollo econ&oacute;mico del Estado, que permitan el impulso de tales sectores: Agricola, Industrial, Comercio, servicios, turismo y artesania, fundamentado en las potencialidades para el desarrollo, que permitan el impulso de tales sectores.<br /> <br /> Direcci&oacute;n: Av. Carabobo Centro Comercial La Galeria<br /> Tel&eacute;fono(s): 0254-2318597/2319757<br /> Correo Electr&oacute;nico: iadey@yaracuy.gob.ve</p>
<p> <a href="#top">^ Arriba</a>&nbsp;</p>
<h3><a name="question_18"></a> Instituto Aut&oacute;nomo de la Salud del Estado Yaracuy (PROSALUD)</h3>
<p>El Instituto Aut&oacute;nomo de la Salud del Estado Yaracuy fue creado con el fin de ejecutar planes, programas y proyectos de ley sanitaria en el territorio del Estado Yaracuy.<br /> <br /> <strong>Misi&oacute;n:</strong><br /> <br /> Es facilitar la gesti&oacute;n estadal en el proceso de transformaci&oacute;n del sector salud, ejerciendo la rector&iacute;a sobre los establecimientos de salud (hospitales, ambulatorios y dispensarios), con el &uacute;nico prop&oacute;sito de lograr un desarrollo humano sustentable dentro del modelo de atenci&oacute;n integral en salud del Estado Yaracuy.<br /> <br /> Direcci&oacute;n: Callejon Cascabel entre Av. cede&ntilde;o y Av. Ravell<br /> Tel&eacute;fono(s): Directo 0254-2318482-/2324419 Fax: 2314912- 2318911<br /> Correo Electr&oacute;nico: prosalud@yaracuy.gob.ve</p>
<p> <a href="#top">^ Arriba</a>&nbsp;</p>
<h3><a name="question_19"></a> Instituto Aut&oacute;nomo de Defensa Civil (IADC)</h3>
<p><strong>Misi&oacute;n:</strong><br /> <br /> El IADC contribuye con la seguridad de los ciudadanos, creando una plataforma organizativa capaz de prevenir, administrar y mitigar emergencias y desastres; el IADC puede efectuar convenios de cooperaci&oacute;n mutua que vayan en pro de nuestra regi&oacute;n, y en el aprovechamiento de la capacidad t&eacute;cnica de su recurso humano por parte de clientes potenciales desde las empresas y personas en general.</p>
<p><strong>Visi&oacute;n:</strong><br /> <br /> Su visi&oacute;n concreta la raz&oacute;n de ser se&ntilde;alada y la proyecta a futuro, mediano y/o largo plazo: &ldquo;llegar a ser una instituci&oacute;n estrat&eacute;gica para el estado en materia de administraci&oacute;n de emergencias y desastres basada en la prevenci&oacute;n, por la salvaguarda y defensa de la calidad de vida de todos los habitantes del territorio YARACUYANO.<br /> <br /> Objetivos:</p>
<ul>
<li>Ejercer funciones de seguridad ciudadana en apoyo a la administraci&oacute;n de emergencias de car&aacute;cter civil y desastres en la judisdcci&oacute;n del estado Yaracuy.</li>
<li>Prestar los servicios y ayudas a la colectividad Yaracuyana, en caso de producirse emergencias y desastres.</li>
<li>Preparar a la poblaci&oacute;n para situaciones imprevistas.</li>
<li>Elaborar los planes y programas de Prevenci&oacute;n, Preparaci&oacute;n, Atenci&oacute;n, y Recuperaci&oacute;n para pobladores en general, en caso de producirse algun desatre o accidente.</li>
</ul>
<p>Direcci&oacute;n: Av. Alberto Ravell con Av. Cartagena<br /> Tel&eacute;fono(s): Directo 0254-2324663 Fax: 2343675.<br /> Correo Electr&oacute;nico:iadc@yaracuy.gob.ve</p>
<p> <a href="#top">^ Arriba</a>&nbsp;</p>
<h3><a name="question_20"></a> Fundaci&oacute;n Regional del Ni&ntilde;o Sim&oacute;n</h3>
<p><strong>Misi&oacute;n:</strong><br /> <br /> Garantizar a los ni&ntilde;os, ni&ntilde;as y adolescentes del Estado Yaracuy&nbsp; a trav&eacute;s del aprovechamiento eficaz y eficiente&nbsp; de los recursos humanos, naturales y financieros para el goce y disfrute de sus derechos humano y el ejercicio pleno de su ciudadan&iacute;a.</p>
<p><strong>Visi&oacute;n:</strong><br /> <br /> Ser reconocida como la Fundaci&oacute;n modelo del pais por su eficiencia en la atenci&oacute;n integral (Salud, Educaci&oacute;n, Deporte, Cultura, Recreaci&oacute;n y nutrici&oacute;n,) a los ni&ntilde;os, ni&ntilde;as y adolescentes, para formar al individuo como ciudadana republicanos a trav&eacute;s de nuestra instituci&oacute;n con el reconocimiento de una excelente gesti&oacute;n y una administraci&oacute;n eficiente en beneficio de los ni&ntilde;os, ni&ntilde;as y adolescentes.<br /> <br /> Objetivos:</p>
<ul>
<li>El objetivo principal de la fundaci&oacute;n del Ni&ntilde;o es ofrecer atenci&oacute;n a las ni&ntilde;as, ni&ntilde;os y adolescentes, para contribuir a su desarrollo integral y en especial, brindarles oportunidades para que disfruten y ejerzan progresivamente todos los derechos y deberes contemplados en la constituci&oacute;n de la Republica Bolivaria de Venezuela, la Ley Organica para la Protecci&oacute;n del Ni&ntilde;o y del Adolescente, la convenci&oacute;n sobre los derechos del ni&ntilde;o y demas tratados internacionales que haya suscrito y ratificado la Rep&uacute;blica.</li>
</ul>
<p>Direcci&oacute;n: Urb. Piedra Grande, Calle Principal Municipio La Independencia.<br /> Tel&eacute;fono(s): Directo 0254-2310259 - 2313485<br /> E-mail: fdelni&ntilde;oyara@cantv.net<br /> Correo Electr&oacute;nico : fundnino@yaracuy.gob.ve</p>
<p> <a href="#top">^ Arriba</a>&nbsp;</p>
<h3><a name="question_23"></a> Instituto Aut&oacute;nomo Cuerpo de Bomberos del Estado Yaracuy (IABOY)</h3>
<p><strong>Misi&oacute;n:</strong><br /> <br /> Generar un ambiente de confianza, seguridad y bienestar a toda la ciudadan&iacute;a yaracuyana, mediante la presentaci&oacute;n de un servicio de atenci&oacute;n a toda emergencia que amanece y desestabilice la vida y patrimonio de las misma, aplicando para ello los niveles estandarizados de prevenci&oacute;n, protecci&oacute;n de eventos, liderizandos la gesti&oacute;n con eficacia y eficiencia, contribuyendo de esta manera con el desarrollo y progreso del estado Yaracuy<br /> <br /> <strong>Visi&oacute;n:</strong><br /> <br /> Somos una instituci&oacute;n publica de servicios social, creada para garantizar a la ciudadan&iacute;a yaracuyana, la seguridad personal ante la presencia de cualquier emergencia y/o evento, que amanece su vida y su patrimonio, a trav&eacute;s de un recurso&nbsp;&nbsp; humano disciplinado, con m&iacute;stica y vocaci&oacute;n de servicio, adem&aacute;s de una formaci&oacute;n profesional de primera contando con los mejores equipos materiales y m&oacute;viles, permiti&eacute;ndose con eficiencia y eficacia las amenazas que puedan desestabilizar la tranquilidad y confort de esa ciudadan&iacute;a<br /> <br /> &nbsp;Objetivo:</p>
<ul>
<li>Organizar y Prestar los Servicios de Investigaci&oacute;n, Prevenci&oacute;n, Protecci&oacute;n y Extinsi&oacute;n de Incendios; de rescate y de servicio auxiliar de asistencia m&eacute;dica de Emergencia.</li>
</ul>
<p>Correo Electr&oacute;nico : iaboy@yaracuy.gob.ve</p>
<p> <a href="#top">^ Arriba</a>&nbsp;</p>
<h3><a name="question_25"></a> Instituto Contra la Pobreza y la Exclusi&oacute;n Social del Estado Yaracuy (IAPESEY)</h3>
<p><strong>Misi&oacute;n:</strong><br /> <br /> IAPESEY, es un instituto aut&oacute;nomo estadal adscrito a la gobernaci&oacute;n del estado Yaracuy; que tiene como misi&oacute;n promover el&nbsp; bienestar y desarrollo social de la poblaci&oacute;n yaracuyana de bajos recursos econ&oacute;micos, mediante el dise&ntilde;o, fortalecimiento y ejecuci&oacute;n de programas sociales exitosos, con un capital humano id&oacute;neo con criterios de eficiencia, eficacia, efectividad, honestidad, amor y compromiso, utilizando tecnolog&iacute;a adecuada, orientados a atender a la mujer, madre, ni&ntilde;os, j&oacute;venes, adultos, mayores, familias y comunidades, integr&aacute;ndolos como actores de desarrollo, para mejorar su calidad de vida<br /> <br /> <strong>Visi&oacute;n:</strong><br /> <br /> Ser un instituto modelo, eficaz y eficiente sustentado en los valores de humildad,&nbsp; equidad, participaci&oacute;n, solidaridad, cooperaci&oacute;n y corresponsabilidad que contribuya al mejoramiento del nivel de vida integral de la poblaci&oacute;n yaracuyana, a trav&eacute;s del dise&ntilde;o, promoci&oacute;n y ejecuci&oacute;n&nbsp; de programas sociales que coadyuven al avance de la de la conformaci&oacute;n de una estructura social, dentro de los objetivos estrat&eacute;gicos del gobierno nacional y por ende en la consolidaci&oacute;n del socialismo del siglo XXI, como modelo de desarrollo econ&oacute;mico y social<br /> <br /> Objetivos:</p>
<ul>
<li>Crear, promocionar, coordinar y ejecutar programas sociales de conformidad con las prioridades y lineamientos establecidos por el gobierno bolivariano del estado Yaracuy.</li>
<li>Fomentar y estimular la participaci&oacute;n de todos los sectores de la comunidad yaracuyana, en actividades dirigidas al desarrollo social y la protecci&oacute;n del ni&ntilde;o, de la madre y la familia.</li>
<li>Promover y ejecutar programas de abastecimiento de productos alimentarios, escolares y de consumo tradicional, a trav&eacute;s de las modalidades que se estima pertinente.</li>
<li>Ampliar los proyectos, mecanismos e instrumentos tendientes a erradicar la pobreza en el estado Yaracuy, bien sea a causa de necesidades sentidas de la poblaci&oacute;n o por desastres naturales.</li>
<li>Desarrollar programas de atenci&oacute;n a los adultos mayores, dirigidos a la dignificaci&oacute;n de su presencia como ciudadanos aptos para el aporte de conocimientos y experiencias a la comunidad.</li>
<li>Promover y desarrollar programas de transporte p&uacute;blico: ruta social, ruta rural y ruta estudiantil, y cualquier otro servicio solidario de transporte dirigidos a la poblaci&oacute;n de escasos recursos econ&oacute;micos.</li>
<li>Desarrollar programas dirigidos a la protecci&oacute;n de la mujer y la familia al desarrollo del ciudadano y de las comunidades.</li>
</ul>
<p>Direcci&oacute;n: 6ta Avenida entre calles 22 y 23<br /> Tel&eacute;fono(s): Directo 0254-2319023/2324587<br /> Correo Electr&oacute;nico:fundesoy@yaracuy.gob.</p>
<p> <a href="#top">^ Arriba</a>&nbsp;</p>
<h3><a name="question_26"></a> Instituto de Habitad y Vivienda del Estado Yaracuy</h3>
<p><strong>Misi&oacute;n:</strong><br /> <br /> Satisfacer las necesidades de vivienda, obras de urbanismo y servicios b&aacute;sicos de las &aacute;reas urbanas y rurales de la poblaci&oacute;n de escasos recursos, orientados bajo una filosof&iacute;a de calidad, con un personal altamente calificado, enmarcado en un liderazgo centrado en principios, preocupado por la innovaci&oacute;n tecnol&oacute;gica; el mejoramiento continuo y la obtenci&oacute;n de financiamiento de organismos nacionales e internacionales, en conformidad a los lineamientos que establezcan el plan de desarrollo del estado y las pol&iacute;ticas nacionales que formule el ejecutivo nacional.<br /> <br /> <strong>Visi&oacute;n:</strong><br /> <br /> Ser un organismo aut&oacute;nomo, rector de la pol&iacute;tica habitacional, de consolidaci&oacute;n y reordenamiento de las &aacute;reas urbanas y rurales de la poblaci&oacute;n de escasos recursos del estado, capaz de disminuir notoriamente el d&eacute;ficit habitacional de las familias Yaracuyanas, bajo criterios de calidad, eficiencia y &eacute;tica, para contribuir con un ambiente digno donde las familias se desarrollen y puedan incorporarse al sistema productivo, esto, contando con un equipo humano comprometido, capacitado, actualizado y orgulloso de pertenecer al instituto.<br /> <br /> Objetivos:</p>
<ul>
<li>El Instituto Aut&oacute;nomo de la Vivienda y Equipamiento de Barrios fue creado con el fin de ejecutar y administrar la pol&iacute;tica de vivienda de inter&eacute;s social, el equipamiento integral de los servicios de infraestructura y la construcci&oacute;n de obras completamente de inter&eacute;s colectivo.</li>
<li>Satisfacer las necesidades de vivienda, obras de urbanismo y servicios b&aacute;sicos de las &aacute;reas urbanas y rurales de la poblaci&oacute;n de escasos recursos del estado, capaz de disminuir notoriamente el d&eacute;ficit habitacional de las familias yaracuyanas.</li>
</ul>
<p>Direcci&oacute;n: Av. 7 esquina calle 7, San Felipe -Edo. Yaracuy.<br /> Tel&eacute;fono(s): 0254-2318754/2318615 <br /> Correo Electronicos: ihavey@yaracuy.gob.ve</p>
<p> <a href="#top">^ Arriba</a>&nbsp;</p>
<h3><a name="question_27"></a> Servicio Aut&oacute;nomo de Administraci&oacute;n de las Infraestructuras del Estado Yaracuy (SAIEY)</h3>
<p><strong>Misi&oacute;n:</strong><br /> <br /> Es un instituto que comercializa, administra y promociona la infraestructura deportiva, cultural y tur&iacute;stica del estado Yaracuy, ofertando espacio f&iacute;sico&nbsp; adecuados, apoyo y accesoria a los entes p&uacute;blicos o privados para la realizaci&oacute;n de eventos de car&aacute;cter estadal, nacional e internacional; optimizando los recursos tecnol&oacute;gicos y financieros necesarios, y un capital&nbsp;&nbsp; humano que trabaja en equipo, responsable y creativo para brindar la mejor atenci&oacute;n a quienes demandan nuestros servicios.<br /> <br /> <strong>Visi&oacute;n:</strong><br /> <br /> El SAIEY es una instituci&oacute;n de car&aacute;cter publico que tendr&aacute; como prop&oacute;sito fundamental la administraci&oacute;n de la infraestructura deportiva, cultural y tur&iacute;stica del estado Yaracuy con el fin de dinamizar la econom&iacute;a regional a trav&eacute;s de la administraci&oacute;n, promoci&oacute;n y realizaci&oacute;n de eventos que, por su importancia, conviertan al estado Yaracuy en una referencia nacional e internacional y al mismo tiempo contribuir con la difusi&oacute;n de las expresiones culturales y tur&iacute;sticas, para coadyuvar de manera eficaz con el desarrollo econ&oacute;mico del estado y el bienestar social. <br /> <br /> Objetivos:</p>
<ul>
<li>Comercializar, administrar y promocionar la infraestructura deportiva, cultural y tur&iacute;stica del estado Yaracuy a trav&eacute;s del ofrecimiento de espacio f&iacute;sico adecuados, la captaci&oacute;n, la promoci&oacute;n,&nbsp;&nbsp; el apoyo y la accesoria para la realizaci&oacute;n de eventos que contribuyan en el desarrollo humano de los ciudadanos de la regi&oacute;n y en dinamizacion&nbsp;&nbsp; de la econom&iacute;a local.</li>
<li>Generar y establecer los lineamientos de administraci&oacute;n, comercializaci&oacute;n y promoci&oacute;n de los servicios y pol&iacute;ticas de funcionamiento de la infraestructura deportiva, cultural y tur&iacute;stica.</li>
<li>Dirigir los recursos econ&oacute;micos tecnol&oacute;gicos y humanos&nbsp; disponibles para el pleno funcionamiento, mantenimiento y fortalecimiento de la infraestructura deportiva, cultural y tur&iacute;stica.</li>
<li>Fomentar la infraestructura deportiva, cultural y tur&iacute;stica, como espacio f&iacute;sico adecuado para la realizaci&oacute;n&nbsp; de eventos de car&aacute;cter estadal, nacional e internacional.</li>
</ul>
<p>Direcci&oacute;n: Av. Alberto Ravell Centro de Convenciones Henrique Tirado Reyes.<br /> Tel&eacute;fono(s): Directo 0254-2319060<br /> Correo Electr&oacute;nico: saiey@yaracuy.gob.ve</p>
<p> <a href="#top">^ Arriba</a>&nbsp;</p>
<h3><a name="question_28"></a> Instituto Aut&oacute;nomo de Deporte del Estado Yaracuy (FUNDEY)</h3>
<p><strong>Misi&oacute;n:</strong></p>
<p>Garantizar el fomento y desarrollo de la actividad deportiva, con bases t&eacute;cnicas, Presupuestarias y Cientificas que nos permitean, a trav&eacute;s de los programas lograr los objetivos trazados.<br /> <br /> <strong>Visi&oacute;n:</strong><br /> <br /> Lograr con nuestras fortalezas program&aacute;ticas el modelo deportivo por excelencia a nivel&nbsp; nacional.<br /> <br /> Objetivos:</p>
<ul>
<li>Garantizar el fomento y desarrollo de la actividad deportiva, con los nuevos avances t&eacute;cnicos a nivel mundial, que nos permitan brindarle una optima atenci&oacute;n a nuestros atletas, con una infraestructura id&oacute;nea para la masificacion y el alto rendimiento.</li>
</ul>
<p>Direcci&oacute;n: Av. Alberto Ravell, frente al IUTY<br /> Tel&eacute;fono(s): Directo 0254-2311346<br /> Correo Electr&oacute;nico: fundey@yaracuy.gob.ve</p>
<p> <a href="#top">^ Arriba</a>&nbsp;</p>
<h3><a name="question_30"></a> Instituto Aut&oacute;nomo de Ayuda de los Funcionarios de Seguridad Ciudadana del Estado Yaracuy (IAA)</h3>
<p>El Instituto Aut&oacute;nomo de Ayuda se cre&oacute; con la necesidad de fortalecer las necesidades de los funcionarios de seguridad ciudadana del Estado Yaracuy.<br /> <br /> <strong>Misi&oacute;n:</strong><br /> <br /> Promover y desarrollar en forma integral el bienestar Social y Econ&oacute;mico de los funcionarios de Seguridad Ciudadana estadales, a los Funcionarios P&uacute;blicos adscritos por convenios, al personal administrativo de estas organizaciones y su carga familiar ( Padre, Conyuge o Concubino (a) e Hijos menores de 18 a&ntilde;os de edad y solteros), a trav&eacute;s de la ejecuci&oacute;n de programas sociales y mediante el aprovechamiento eficaz y eficiente de los recursos que est&eacute;n orientados a mejorar su calidad de vida.<br /> <br /> <strong>Visi&oacute;n:</strong><br /> <br /> Ser un instituto modelo de Desarrollo Humano y Econ&oacute;micamente sustentable, que aprovecha sus recursos humanos, tecnol&oacute;gicos y financieros en la integridad de la seguridad social. Un organismo efectivo en la presentaci&oacute;n de los servicios medico-asistenciales, odontol&oacute;gicos y alimenticios, que mejoren la calidad de vida del funcionario afiliado y su carga familiar de ley.<br /> <br /> Objetivos:</p>
<ul>
<li>Coordinar y ejecutar programas de desarrollo social de acuerdo a los lineamientos establecidos por el Gobierno Bolivariano y socialista del estado Yaracuy.</li>
<li>Mejorar la calidad de vida de los funcionarios de seguridad Ciudaddana y su carga familiar de ley, otorgandoles los beneficios de Consultas y ex&aacute;menes Especializados, Medicinas, Lentes Correctivos, Botas Ortopedicas, Servicios Funerarios, Intervenciones Quirurgicas, Traslados en Ambulancia, servicio de Enfermeria, ayudas para Estudios Superiores y Alimentos entre otros.</li>
<li>Fomentar y ejecutar Programas Medico-Asistenciales, Odotol&oacute;gicos, de Hospitalizaci&oacute;n y Cirug&iacute;a.</li>
<li>Fomentar y ejecutar Programas que aumenten la accesibilidad a los servicios de Laboratorio Clinico.</li>
<li>Promover y ejecutar Programas de suministro y seguridad alimentaria, con productos de la cesta b&aacute;sica, a trav&eacute;s de la modalidades que se emiten</li>
<li>Brindar asesorias juridicas a los afiliados, a fin de prestar apoyo en problemas Legales, Habitacionales, Penales y Laborales</li>
</ul>
<p>Direcci&oacute;n: Urb. Andr&eacute;s Eloy Blanco, Calle 6 entre Av. 3<br /> Tel&eacute;fono(s): Directo 0254-2345362<br /> Correo Electr&oacute;nico: iaa@yaracuy.gob.ve</p>
<p> <a href="#top">^ Arriba</a>&nbsp;</p>
<h3><a name="question_77"></a> Servicio Integral de Emegencias del Estado Yaracuy 171</h3>
<p>Es un centro de atenci&oacute;n a la ciudadan&iacute;a, que se encarga de integrar y coordinar los cuerpos de seguridad competentes, en caso de situaciones de emergencias y solicitudes de servicios, para as&iacute; brindar mayor seguridad y confianza al usuario.</p>
<p>Misi&oacute;n</p>
<p>Ser un ente de apoyo de los organismos de seguridad y emergencias del Estado Yaracuy a trav&eacute;s de un trabajo coordinado para dar respuesta lo m&aacute;s inmediato posible al ciudadano que haga uso del servicio, prestando atenci&oacute;n las 24 horas del d&iacute;a, los 365 d&iacute;as del a&ntilde;o, que permita contribuir con la seguridad de la ciudadan&iacute;a Yaracuyana.</p>
<p>Visi&oacute;n</p>
<p>Ser una instituci&oacute;n &eacute;lite al servicio de la ciudadan&iacute;a, estableciendo un sistema de coordinaci&oacute;n e integraci&oacute;n de los cuerpos de seguridad y emergencias del Estado, que garanticen respuesta al llamado y generen en la colectividad confianza de ser atendidos, todo ello, fundamentados en criterios de excelencia, efectividad, eficiencia y eficacia, para convertirse en el mejor centro de atenci&oacute;n de llamadas de emergencias a nivel nacional.</p>
<p>Objetivos y Estrategias</p>
<ul>
<li>Satisfacer de forma inmediata y eficiente a la ciudadan&iacute;a en materia de emergencia, prevenci&oacute;n y seguridad.</li>
<li>Establecer estrategias dirigidas a la preparaci&oacute;n de las comunidades, que garanticen el aprovechamiento del potencial personal, familiar y comunitario para enfrentar emergencias.</li>
<li>Establecer convenios entre empresas p&uacute;blicas y privadas, para lograr alianzas estrat&eacute;gicas en beneficio de la seguridad de la ciudadan&iacute;a.</li>
<li>Garantizar un servicio de &oacute;ptima calidad, proporcion&aacute;ndoles una respuesta inmediata a las emergencias para nuestra ciudadan&iacute;a.</li>
<li>Unificar criterios de informaci&oacute;n y comunicaci&oacute;n entre los organismos de segura p&uacute;blica nacional y de los Estados vecinos.</li>
<li>Lograr la autogesti&oacute;n para aminorar las cargas del Estado.</li>
<li>Establecer convenios institucionales y lograr alianzas estrat&eacute;gicas en beneficio de la seguridad de la ciudadan&iacute;a.</li>
<li>Supervisar las comunicaciones de todos los cuerpos de seguridad y de emergencias del Estado Yaracuy.</li>
</ul>
<p>Direcci&oacute;n: Av. Jose Joaquin Veroes con calle 14 edifico Invity<br /> Tel&eacute;fono(s): Directo <br /> Correo Electr&oacute;nico:</p>
	</div>
</article>